# Generated by Django 5.2.17 on 2026-08-19 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0002_alter_schoolmembership_status'),
        ('schools', '0003_schoolsettings_morning_late_grace_minutes_and_more'),
        ('student_warnings', '0001_initial'),
        ('students', '0003_section_qr_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('TEACHER', 'معلم'), ('VICE_PRINCIPAL', 'وكيل'), ('SCHOOL_MANAGER', 'مدير المدرسة')], max_length=20)),
                ('category', models.CharField(choices=[('ATTENDANCE', 'المواظبة'), ('ACADEMIC', 'الأداء الدراسي'), ('CLASSROOM_BEHAVIOR', 'سلوك صفي'), ('SOCIAL', 'اجتماعي'), ('OTHER', 'أخرى')], max_length=20)),
                ('reason_code', models.CharField(choices=[('REPEATED_ABSENCE', 'غياب متكرر'), ('REPEATED_MORNING_LATE', 'تأخر صباحي متكرر'), ('WARNING_ESCALATION', 'بلوغ إنذار'), ('NO_IMPROVEMENT', 'عدم تحسن بعد الإنذار'), ('OTHER_ATTENDANCE', 'سبب مواظبة آخر'), ('ACADEMIC_WEAKNESS', 'ضعف دراسي'), ('ACADEMIC_DECLINE', 'تراجع دراسي'), ('HOMEWORK_NONCOMPLIANCE', 'عدم إنجاز المهام'), ('LOW_PARTICIPATION', 'عدم المشاركة'), ('OTHER_ACADEMIC', 'سبب دراسي آخر'), ('SLEEPING_IN_CLASS', 'النوم داخل الحصة'), ('REPEATED_DISTRACTION', 'تشتت متكرر'), ('CLASSROOM_DISRUPTION', 'سلوك يؤثر في التعلم'), ('LEARNING_BEHAVIOR_CONCERN', 'سلوك تعلمي يحتاج متابعة'), ('OTHER_CLASSROOM', 'سبب صفي آخر'), ('PEER_INTERACTION_CONCERN', 'مشكلة في التفاعل مع الزملاء'), ('ISOLATION_CONCERN', 'انعزال ملحوظ'), ('OTHER_SOCIAL', 'سبب اجتماعي آخر'), ('COUNSELOR_MEETING_REQUEST', 'طلب مقابلة المرشد'), ('OTHER_GENERAL', 'سبب آخر')], max_length=30)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('NEW', 'جديدة'), ('ACKNOWLEDGED', 'تم الاستلام'), ('CLOSED', 'مغلقة'), ('CANCELLED', 'ملغاة')], default='NEW', max_length=15)),
                ('priority', models.CharField(choices=[('NORMAL', 'عادية'), ('HIGH', 'عاجلة')], default='NORMAL', max_length=10)),
                ('snapshot_data', models.JSONField(blank=True, default=dict)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_reason', models.CharField(blank=True, default='', max_length=300)),
                ('assigned_counselor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_referrals', to='memberships.schoolmembership')),
                ('closed_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='memberships.schoolmembership')),
                ('created_by_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='memberships.schoolmembership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_referrals', to='schools.school')),
                ('source_warning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='student_warnings.studentwarning')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='students.student')),
            ],
            options={
                'verbose_name': 'إحالة طالب',
                'verbose_name_plural': 'إحالات الطلاب',
            },
        ),
        migrations.CreateModel(
            name='StudentReferralContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observation_type', models.CharField(choices=[('CLASSROOM_OBSERVATION', 'ملاحظة صفية'), ('ACADEMIC_OBSERVATION', 'ملاحظة دراسية'), ('ATTENDANCE_OBSERVATION', 'ملاحظة مواظبة'), ('COUNSELOR_INTAKE_NOTE', 'ملاحظة استلام المرشد'), ('OTHER_OBSERVATION', 'ملاحظة أخرى')], max_length=25)),
                ('notes', models.TextField(max_length=1000)),
                ('created_by_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='memberships.schoolmembership')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='referrals.studentreferral')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
            options={
                'verbose_name': 'ملاحظة على إحالة',
                'verbose_name_plural': 'ملاحظات الإحالات',
            },
        ),
        migrations.CreateModel(
            name='StudentReferralEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'أنشئت الإحالة'), ('ASSIGNED', 'تم تعيين مرشد'), ('REASSIGNED', 'تم تغيير المرشد'), ('ACKNOWLEDGED', 'تم استلام الإحالة'), ('CONTRIBUTION_ADDED', 'أضيفت ملاحظة'), ('CLOSED', 'أُغلقت الإحالة'), ('CANCELLED', 'أُلغيت الإحالة')], max_length=25)),
                ('metadata_safe', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='memberships.schoolmembership')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='referrals.studentreferral')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
            options={
                'verbose_name': 'حدث إحالة',
                'verbose_name_plural': 'أحداث الإحالات',
            },
        ),
        migrations.AddIndex(
            model_name='studentreferral',
            index=models.Index(fields=['school', 'student', 'status'], name='referral_student_idx'),
        ),
        migrations.AddIndex(
            model_name='studentreferral',
            index=models.Index(fields=['school', 'assigned_counselor_membership', 'status'], name='referral_counselor_idx'),
        ),
        migrations.AddIndex(
            model_name='studentreferral',
            index=models.Index(fields=['school', 'category', 'status'], name='referral_category_idx'),
        ),
        migrations.AddIndex(
            model_name='studentreferral',
            index=models.Index(fields=['school', '-created_at'], name='referral_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentreferral',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', False), ('status__in', ['CLOSED', 'CANCELLED'])), models.Q(('closed_at__isnull', True), ('status__in', ['NEW', 'ACKNOWLEDGED'])), _connector='OR'), name='referral_closed_at_matches_status'),
        ),
        migrations.AddIndex(
            model_name='studentreferralcontribution',
            index=models.Index(fields=['referral', 'created_at'], name='contribution_time_idx'),
        ),
        migrations.AddIndex(
            model_name='studentreferralevent',
            index=models.Index(fields=['referral', 'created_at'], name='referral_event_idx'),
        ),
    ]
