# Generated by Django 5.2.17 on 2026-08-18 15:40

import django.db.models.deletion
import students.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("schools", "0002_schoolsettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="اسم الصف")),
                ("code", models.CharField(max_length=50, verbose_name="الرمز")),
                ("sequence", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "صف",
                "verbose_name_plural": "الصفوف",
                "ordering": ["sequence", "code"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, verbose_name="اسم الفصل")),
                ("code", models.CharField(max_length=50, verbose_name="الرمز")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="students.grade",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "فصل",
                "verbose_name_plural": "الفصول",
                "ordering": ["grade__sequence", "code"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("national_id_encrypted", models.TextField()),
                ("national_id_lookup_hash", models.CharField(max_length=64)),
                ("national_id_masked", models.CharField(max_length=12)),
                (
                    "student_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="اسم الطالب"),
                ),
                (
                    "guardian_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "guardian_mobile",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "منتظم"),
                            ("INACTIVE", "غير نشط"),
                            ("TRANSFERRED", "منقول"),
                            ("GRADUATED", "متخرج"),
                            ("ARCHIVED", "مؤرشف"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "طالب",
                "verbose_name_plural": "الطلاب",
            },
        ),
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "منتظم"),
                            ("TRANSFERRED", "منقول"),
                            ("COMPLETED", "مكتمل"),
                            ("WITHDRAWN", "منسحب"),
                            ("ARCHIVED", "مؤرشف"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("enrolled_at", models.DateField()),
                ("ended_at", models.DateField(blank=True, null=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="students.grade",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="schools.school",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="students.section",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "قيد دراسي",
                "verbose_name_plural": "القيود الدراسية",
            },
        ),
        migrations.CreateModel(
            name="StudentImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=students.models.import_file_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "مرفوع"),
                            ("PROCESSING", "قيد المعالجة"),
                            ("READY_FOR_REVIEW", "جاهز للمراجعة"),
                            ("IMPORTING", "جارٍ الاستيراد"),
                            ("COMPLETED", "مكتمل"),
                            ("FAILED", "فشل"),
                            ("CANCELLED", "ملغى"),
                        ],
                        default="UPLOADED",
                        max_length=20,
                    ),
                ),
                ("column_mapping", models.JSONField(blank=True, default=dict)),
                ("headers", models.JSONField(blank=True, default=list)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("valid_rows", models.PositiveIntegerField(default=0)),
                ("invalid_rows", models.PositiveIntegerField(default=0)),
                ("duplicate_rows", models.PositiveIntegerField(default=0)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, default="", max_length=50)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_jobs",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to="schools.school",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "مهمة استيراد طلاب",
                "verbose_name_plural": "مهام استيراد الطلاب",
            },
        ),
        migrations.CreateModel(
            name="StudentImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("national_id_encrypted", models.TextField(blank=True, default="")),
                (
                    "national_id_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "جديد"),
                            ("EXISTING_UNCHANGED", "بلا تغيير"),
                            ("EXISTING_UPDATED", "تحديث بيانات"),
                            ("SECTION_CHANGED", "انتقال فصل"),
                            ("GRADE_CHANGED", "تغير صف"),
                            ("ERROR", "خطأ"),
                            ("DUPLICATE_IN_FILE", "مكرر في الملف"),
                        ],
                        max_length=30,
                    ),
                ),
                ("error_codes", models.JSONField(blank=True, default=list)),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="students.studentimportjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "صف استيراد",
                "verbose_name_plural": "صفوف الاستيراد",
                "ordering": ["row_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.UniqueConstraint(
                fields=("school", "code"), name="uniq_grade_code_per_school"
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["school", "grade"], name="section_school_grade_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("school", "grade", "code"), name="uniq_section_code_per_grade"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["school", "status"], name="student_school_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["school", "full_name"], name="student_school_name_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("school", "national_id_lookup_hash"),
                name="uniq_student_nid_per_school",
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                condition=models.Q(("student_number__isnull", False)),
                fields=("school", "student_number"),
                name="uniq_student_number_per_school",
            ),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["school", "academic_year", "status"],
                name="enroll_school_year_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["section", "status"], name="enroll_section_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("student", "academic_year"),
                name="uniq_active_enrollment_per_year",
            ),
        ),
        migrations.AddIndex(
            model_name="studentimportjob",
            index=models.Index(
                fields=["school", "status"], name="import_school_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentimportjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PROCESSING", "IMPORTING"])),
                fields=("school",),
                name="uniq_running_import_per_school",
            ),
        ),
        migrations.AddIndex(
            model_name="studentimportrow",
            index=models.Index(
                fields=["job", "status"], name="import_row_job_status_idx"
            ),
        ),
    ]
