# Generated by Django 5.2.17 on 2026-08-18 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_schoolsettings"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="exit_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="exit_reason",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="student",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="status_changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "نشط"),
                    ("GRADUATED", "متخرج"),
                    ("TRANSFERRED", "منتقل"),
                    ("WITHDRAWN", "منسحب"),
                    ("INACTIVE", "غير نشط"),
                    ("ARCHIVED", "مؤرشف"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="StudentPurgeJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.CharField(blank=True, default="", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "بانتظار التنفيذ"),
                            ("RUNNING", "قيد التنفيذ"),
                            ("COMPLETED", "مكتمل"),
                            ("PARTIALLY_FAILED", "مكتمل جزئيًا"),
                            ("FAILED", "فشل"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("student_ids", models.JSONField(blank=True, default=list)),
                ("total_students", models.PositiveIntegerField(default=0)),
                ("processed_students", models.PositiveIntegerField(default=0)),
                ("deleted_students", models.PositiveIntegerField(default=0)),
                ("failed_students", models.PositiveIntegerField(default=0)),
                ("db_records_deleted", models.PositiveIntegerField(default=0)),
                ("storage_objects_deleted", models.PositiveIntegerField(default=0)),
                ("storage_objects_failed", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purge_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purge_jobs",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "مهمة حذف نهائي",
                "verbose_name_plural": "مهام الحذف النهائي",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["PENDING", "RUNNING"])),
                        fields=("school",),
                        name="uniq_running_purge_per_school",
                    )
                ],
            },
        ),
    ]
