# Generated by Django 5.2.17 on 2026-08-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_exit_date_student_exit_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="qr_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
