# Generated by Django 5.2.17 on 2026-09-29 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_section_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merged_duplicates",
                to="students.student",
            ),
        ),
    ]
