# Generated by Django 5.2.17 on 2026-09-29 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0004_school_school_type"),
        ("students", "0005_section_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolSmsIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("DREAMS", "دريمز"), ("MSEGAT", "مسجات")],
                        max_length=12,
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("secret_encrypted", models.TextField()),
                ("sender_name", models.CharField(max_length=30)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_integration",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "ربط الرسائل النصية للمدرسة",
                "verbose_name_plural": "روابط الرسائل النصية للمدارس",
            },
        ),
        migrations.CreateModel(
            name="AbsenceSmsNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attendance_date", models.DateField()),
                ("absence_status", models.CharField(max_length=14)),
                (
                    "provider",
                    models.CharField(
                        choices=[("DREAMS", "دريمز"), ("MSEGAT", "مسجات")],
                        max_length=12,
                    ),
                ),
                ("recipient_masked", models.CharField(max_length=20)),
                ("recipient_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "بانتظار الإرسال"),
                            ("SENDING", "جارٍ الإرسال"),
                            ("ACCEPTED", "قبله المزود"),
                            ("FAILED", "تعذر الإرسال"),
                            ("UNKNOWN", "تحتاج مراجعة حالة الإرسال"),
                        ],
                        default="QUEUED",
                        max_length=12,
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "failure_code",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=1)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absence_sms_notices",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="absence_sms_notices",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار غياب نصي",
                "verbose_name_plural": "إشعارات الغياب النصية",
                "indexes": [
                    models.Index(
                        fields=["school", "attendance_date"],
                        name="sms_notice_school_date_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "student", "attendance_date"),
                        name="uniq_absence_sms_student_day",
                    )
                ],
            },
        ),
    ]
