# Generated by Django 5.2.17 on 2026-09-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("memberships", "0002_alter_schoolmembership_status"),
        ("schools", "0003_schoolsettings_morning_late_grace_minutes_and_more"),
        ("students", "0003_section_qr_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentLeavePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("leave_date", models.DateField(verbose_name="تاريخ الاستئذان")),
                ("leave_time", models.TimeField(verbose_name="وقت الخروج")),
                ("reason", models.CharField(max_length=500, verbose_name="سبب الاستئذان")),
                ("grade_name", models.CharField(blank=True, default="", max_length=100)),
                ("section_name", models.CharField(blank=True, default="", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "ساري"), ("CANCELLED", "ملغى")],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancellation_reason",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "cancelled_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_leaves",
                        to="memberships.schoolmembership",
                    ),
                ),
                (
                    "recorded_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_leaves",
                        to="memberships.schoolmembership",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_leave_permissions",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_permissions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "استئذان طالب",
                "verbose_name_plural": "استئذانات الطلاب",
                "ordering": ["-leave_date", "-leave_time", "-id"],
                "indexes": [
                    models.Index(
                        fields=["school", "leave_date", "status"],
                        name="leave_school_date_status_idx",
                    ),
                    models.Index(
                        fields=["school", "student", "-leave_date"],
                        name="leave_school_student_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "ACTIVE")),
                        fields=("school", "student", "leave_date"),
                        name="uniq_active_student_leave_day",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("cancelled_at__isnull", True), ("status", "ACTIVE")),
                            models.Q(("cancelled_at__isnull", False), ("status", "CANCELLED")),
                            _connector="OR",
                        ),
                        name="leave_cancelled_requires_timestamp",
                    ),
                ],
            },
        ),
    ]
