# Generated by Django 5.2 on 2026-09-09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_leaves", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentleavepermission",
            name="recipient_id_last4",
            field=models.CharField(blank=True, default="", max_length=4, verbose_name="آخر أربعة أرقام من هوية المستلم"),
        ),
        migrations.AddField(
            model_name="studentleavepermission",
            name="recipient_name",
            field=models.CharField(blank=True, default="", max_length=150, verbose_name="اسم المستلم"),
        ),
        migrations.AddField(
            model_name="studentleavepermission",
            name="recipient_relationship",
            field=models.CharField(blank=True, default="", max_length=60, verbose_name="صفة المستلم"),
        ),
        migrations.CreateModel(
            name="StudentGateRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("released_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "leave_permission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gate_release",
                        to="student_leaves.studentleavepermission",
                    ),
                ),
                (
                    "released_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_gate_releases",
                        to="memberships.schoolmembership",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_gate_releases",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "خروج طالب من البوابة",
                "verbose_name_plural": "خروج الطلاب من البوابة",
                "ordering": ["-released_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["school", "released_at"],
                        name="gate_release_school_time_idx",
                    )
                ],
            },
        ),
    ]
