# Generated by Django 5.2.17 on 2026-08-20 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0002_alter_schoolmembership_status'),
        ('referrals', '0001_initial'),
        ('schools', '0003_schoolsettings_morning_late_grace_minutes_and_more'),
        ('students', '0003_section_qr_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'مفتوحة'), ('UNDER_ASSESSMENT', 'قيد الدراسة'), ('FOLLOW_UP_ACTIVE', 'متابعة جارية'), ('RESOLVED', 'تم التحسن'), ('CLOSED', 'مغلقة')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('NORMAL', 'عادية'), ('HIGH', 'مرتفعة')], default='NORMAL', max_length=10)),
                ('opened_at', models.DateTimeField()),
                ('snapshot_data', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True, default='', max_length=2000)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_reason', models.CharField(blank=True, choices=[('GOALS_MET', 'تحققت أهداف الخطة'), ('IMPROVED', 'تحسن الطالب'), ('NO_LONGER_REQUIRES_FOLLOW_UP', 'لم تعد المتابعة لازمة'), ('TRANSFERRED', 'انتقل الطالب'), ('GRADUATED', 'تخرج الطالب'), ('REFERRED_EXTERNALLY', 'أُحيل لجهة خارجية'), ('OTHER', 'سبب آخر')], default='', max_length=32)),
                ('outcome_summary', models.TextField(blank=True, default='', max_length=2000)),
                ('improvement_status', models.CharField(blank=True, choices=[('IMPROVED', 'تحسن'), ('PARTIALLY_IMPROVED', 'تحسن جزئي'), ('UNCHANGED', 'بلا تغيير'), ('WORSENED', 'تراجع'), ('NOT_ASSESSED', 'لم يقيّم')], default='', max_length=20)),
                ('last_activity_at', models.DateTimeField()),
                ('assigned_counselor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselor_cases', to='memberships.schoolmembership')),
                ('closed_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='memberships.schoolmembership')),
                ('opened_by_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='memberships.schoolmembership')),
                ('primary_referral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='referrals.studentreferral')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_cases', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counselor_cases', to='students.student')),
            ],
            options={
                'verbose_name': 'حالة إرشادية',
                'verbose_name_plural': 'الحالات الإرشادية',
            },
        ),
        migrations.CreateModel(
            name='CounselorCaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CASE_OPENED', 'فتح الحالة'), ('SESSION_ADDED', 'إضافة جلسة'), ('SESSION_VOIDED', 'إلغاء جلسة'), ('PLAN_CREATED', 'إنشاء خطة'), ('PLAN_ACTIVATED', 'تفعيل خطة'), ('PLAN_COMPLETED', 'إكمال خطة'), ('PLAN_CANCELLED', 'إلغاء خطة'), ('GOAL_ADDED', 'إضافة هدف'), ('GOAL_COMPLETED', 'تحقق هدف'), ('ACTIVITY_ADDED', 'إضافة إجراء'), ('ACTIVITY_COMPLETED', 'تنفيذ إجراء'), ('TEACHER_FOLLOW_UP_REQUESTED', 'طلب متابعة معلم'), ('TEACHER_RESPONSE_RECEIVED', 'ورود رد معلم'), ('STATUS_CHANGED', 'تغيير الحالة'), ('COUNSELOR_REASSIGNED', 'تغيير المرشد'), ('CASE_CLOSED', 'إغلاق الحالة'), ('CASE_REOPENED', 'إعادة فتح الحالة')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='memberships.schoolmembership')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='counseling.counselorcase')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
            options={
                'verbose_name': 'حدث حالة',
                'verbose_name_plural': 'أحداث الحالات',
            },
        ),
        migrations.CreateModel(
            name='CounselorFollowUpPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('ACTIVE', 'نشطة'), ('COMPLETED', 'مكتملة'), ('CANCELLED', 'ملغاة')], default='DRAFT', max_length=10)),
                ('start_date', models.DateField()),
                ('target_end_date', models.DateField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='', max_length=2000)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='counseling.counselorcase')),
                ('created_by_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='memberships.schoolmembership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
            options={
                'verbose_name': 'خطة متابعة',
                'verbose_name_plural': 'خطط المتابعة',
            },
        ),
        migrations.CreateModel(
            name='CounselorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_type', models.CharField(choices=[('STUDENT_MEETING', 'مقابلة الطالب'), ('PARENT_MEETING', 'مقابلة ولي الأمر'), ('PHONE_CALL', 'اتصال هاتفي'), ('TEACHER_CONSULTATION', 'تشاور مع معلم'), ('CASE_REVIEW', 'مراجعة الحالة'), ('OTHER', 'أخرى')], max_length=24)),
                ('occurred_at', models.DateTimeField()),
                ('summary', models.TextField(max_length=2000)),
                ('observations', models.TextField(blank=True, default='', max_length=2000)),
                ('outcome', models.TextField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('RECORDED', 'مسجلة'), ('VOIDED', 'ملغاة')], default='RECORDED', max_length=10)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, default='', max_length=300)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='counseling.counselorcase')),
                ('created_by_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='memberships.schoolmembership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('voided_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='memberships.schoolmembership')),
            ],
            options={
                'verbose_name': 'جلسة إرشادية',
                'verbose_name_plural': 'الجلسات الإرشادية',
            },
        ),
        migrations.CreateModel(
            name='FollowUpActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('STUDENT_CHECK_IN', 'متابعة مع الطالب'), ('PARENT_CONTACT', 'تواصل مع ولي الأمر'), ('TEACHER_OBSERVATION', 'طلب ملاحظة معلم'), ('ATTENDANCE_REVIEW', 'مراجعة المواظبة'), ('BEHAVIOR_OBSERVATION', 'ملاحظة سلوكية'), ('FOLLOW_UP_MEETING', 'لقاء متابعة'), ('OTHER', 'أخرى')], max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'قيد التنفيذ'), ('COMPLETED', 'منفذ'), ('CANCELLED', 'ملغى')], default='PENDING', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='memberships.schoolmembership')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='counseling.counselorfollowupplan')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
            options={
                'verbose_name': 'إجراء متابعة',
                'verbose_name_plural': 'إجراءات المتابعة',
            },
        ),
        migrations.CreateModel(
            name='FollowUpGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal_type', models.CharField(choices=[('ATTENDANCE', 'المواظبة'), ('MORNING_LATENESS', 'التأخر الصباحي'), ('PERIOD_LATENESS', 'التأخر عن الحصص'), ('ACADEMIC', 'الأداء الدراسي'), ('CLASSROOM_BEHAVIOR', 'السلوك الصفي'), ('PARTICIPATION', 'المشاركة'), ('CUSTOM', 'هدف مخصص')], max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('baseline_value', models.IntegerField(blank=True, null=True)),
                ('target_value', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'قائم'), ('COMPLETED', 'تحقق'), ('CANCELLED', 'ملغى')], default='OPEN', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='counseling.counselorfollowupplan')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
            options={
                'verbose_name': 'هدف متابعة',
                'verbose_name_plural': 'أهداف المتابعة',
            },
        ),
        migrations.CreateModel(
            name='TeacherFollowUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('ACADEMIC_OBSERVATION', 'ملاحظة دراسية'), ('CLASSROOM_BEHAVIOR', 'سلوك صفي'), ('PARTICIPATION', 'المشاركة'), ('HOMEWORK', 'الواجبات'), ('ATTENDANCE_OBSERVATION', 'ملاحظة مواظبة'), ('CUSTOM', 'أخرى')], max_length=24)),
                ('question', models.TextField(max_length=1000)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'بانتظار الرد'), ('ANSWERED', 'تم الرد'), ('CANCELLED', 'ملغى')], default='PENDING', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_requests', to='counseling.counselorcase')),
                ('requested_by_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='memberships.schoolmembership')),
                ('requested_from_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='memberships.schoolmembership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
            options={
                'verbose_name': 'طلب متابعة معلم',
                'verbose_name_plural': 'طلبات متابعة المعلمين',
            },
        ),
        migrations.CreateModel(
            name='TeacherFollowUpResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observation', models.TextField(max_length=2000)),
                ('improvement_status', models.CharField(max_length=24)),
                ('notes', models.TextField(blank=True, default='', max_length=1000)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='counseling.teacherfollowuprequest')),
                ('responded_by_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='memberships.schoolmembership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
            options={
                'verbose_name': 'رد متابعة معلم',
                'verbose_name_plural': 'ردود متابعة المعلمين',
            },
        ),
        migrations.AddIndex(
            model_name='counselorcase',
            index=models.Index(fields=['school', 'assigned_counselor_membership', 'status'], name='case_school_counselor_idx'),
        ),
        migrations.AddIndex(
            model_name='counselorcase',
            index=models.Index(fields=['school', 'student', 'status'], name='case_school_student_idx'),
        ),
        migrations.AddIndex(
            model_name='counselorcase',
            index=models.Index(fields=['school', '-last_activity_at'], name='case_school_activity_idx'),
        ),
        migrations.AddConstraint(
            model_name='counselorcase',
            constraint=models.UniqueConstraint(fields=('primary_referral',), name='uniq_case_per_referral'),
        ),
        migrations.AddConstraint(
            model_name='counselorcase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CLOSED'), _negated=True), models.Q(('closed_at__isnull', False), models.Q(('closure_reason', ''), _negated=True)), _connector='OR'), name='case_closed_requires_reason'),
        ),
        migrations.AddIndex(
            model_name='counselorcaseevent',
            index=models.Index(fields=['case', '-created_at'], name='caseevent_case_time_idx'),
        ),
        migrations.AddIndex(
            model_name='counselorfollowupplan',
            index=models.Index(fields=['case', 'status'], name='plan_case_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='counselorfollowupplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('case',), name='uniq_active_plan_per_case'),
        ),
        migrations.AddIndex(
            model_name='counselorsession',
            index=models.Index(fields=['case', '-occurred_at'], name='session_case_time_idx'),
        ),
        migrations.AddIndex(
            model_name='counselorsession',
            index=models.Index(fields=['school', 'session_type'], name='session_school_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='counselorsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'VOIDED'), _negated=True), ('voided_at__isnull', False), _connector='OR'), name='session_voided_requires_timestamp'),
        ),
        migrations.AddIndex(
            model_name='followupactivity',
            index=models.Index(fields=['plan', 'status', 'due_date'], name='activity_plan_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='followupactivity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('completed_at__isnull', False), _connector='OR'), name='activity_completed_requires_timestamp'),
        ),
        migrations.AddIndex(
            model_name='followupgoal',
            index=models.Index(fields=['plan', 'status'], name='goal_plan_status_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherfollowuprequest',
            index=models.Index(fields=['school', 'requested_from_membership', 'status'], name='req_school_teacher_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherfollowuprequest',
            index=models.Index(fields=['case', 'status'], name='req_case_status_idx'),
        ),
    ]
