# Generated by Django 5.2.18 on 2026-10-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("counseling", "0002_remove_period_lateness"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counselorcaseevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CASE_OPENED", "فتح الحالة"),
                    ("SESSION_ADDED", "إضافة جلسة"),
                    ("SESSION_VOIDED", "إلغاء جلسة"),
                    ("PLAN_CREATED", "إنشاء خطة"),
                    ("PLAN_ACTIVATED", "تفعيل خطة"),
                    ("PLAN_COMPLETED", "إكمال خطة"),
                    ("PLAN_CANCELLED", "إلغاء خطة"),
                    ("GOAL_ADDED", "إضافة هدف"),
                    ("GOAL_COMPLETED", "تحقق هدف"),
                    ("ACTIVITY_ADDED", "إضافة إجراء"),
                    ("ACTIVITY_COMPLETED", "تنفيذ إجراء"),
                    ("TEACHER_FOLLOW_UP_REQUESTED", "طلب متابعة معلم"),
                    ("TEACHER_RESPONSE_RECEIVED", "ورود رد معلم"),
                    ("STATUS_CHANGED", "تغيير الحالة"),
                    ("COUNSELOR_REASSIGNED", "تغيير المرشد"),
                    ("CASE_CLOSED", "إغلاق الحالة"),
                    ("CASE_REOPENED", "إعادة فتح الحالة"),
                    ("FAMILY_CONTENT_PUBLISHED", "نشر توصية للأسرة"),
                    ("FAMILY_CONTENT_ACKNOWLEDGED", "اطلاع الأسرة على التوصية"),
                    ("FAMILY_ACTION_COMPLETED", "تأكيد الأسرة تنفيذ الإجراء"),
                    ("FAMILY_CONTENT_REVOKED", "سحب توصية الأسرة"),
                ],
                max_length=32,
            ),
        ),
    ]
