# Generated by Django 5.2.17 on 2026-08-19 16:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("memberships", "0002_alter_schoolmembership_status"),
        ("schools", "0003_schoolsettings_morning_late_grace_minutes_and_more"),
        ("students", "0003_section_qr_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentWarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "warning_type",
                    models.CharField(
                        choices=[
                            ("UNEXCUSED_FULL_DAY_ABSENCE", "غياب يوم كامل بدون عذر"),
                            ("MORNING_LATE_OCCURRENCES", "التأخر عن الدوام الصباحي"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("LEVEL_1", "الإنذار الأول"),
                            ("LEVEL_2", "الإنذار الثاني"),
                            ("LEVEL_3", "الإنذار الثالث"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ISSUED", "صادر"), ("VOIDED", "ملغى")],
                        default="ISSUED",
                        max_length=10,
                    ),
                ),
                ("threshold_at_issue", models.PositiveSmallIntegerField()),
                ("metric_value_at_issue", models.PositiveSmallIntegerField()),
                ("student_name_snapshot", models.CharField(max_length=150)),
                (
                    "grade_name_snapshot",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "section_name_snapshot",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "national_id_masked_snapshot",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "full_absence_days_at_issue",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "unexcused_full_absence_days_at_issue",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "excused_full_absence_days_at_issue",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "absent_periods_at_issue",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "unexcused_absent_periods_at_issue",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "morning_late_occurrences_at_issue",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "morning_late_minutes_at_issue",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "period_late_occurrences_at_issue",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "period_late_minutes_at_issue",
                    models.PositiveIntegerField(default=0),
                ),
                ("issued_at", models.DateTimeField()),
                ("notes", models.CharField(blank=True, default="", max_length=300)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_warnings",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "issued_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="memberships.schoolmembership",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_warnings",
                        to="schools.school",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_warnings",
                        to="academics.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warnings",
                        to="students.student",
                    ),
                ),
                (
                    "voided_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="memberships.schoolmembership",
                    ),
                ),
            ],
            options={
                "verbose_name": "إنذار طالب",
                "verbose_name_plural": "إنذارات الطلاب",
                "indexes": [
                    models.Index(
                        fields=["school", "student", "warning_type", "level"],
                        name="warn_school_student_type_idx",
                    ),
                    models.Index(
                        fields=["school", "issued_at"], name="warn_school_issued_idx"
                    ),
                    models.Index(
                        fields=["school", "academic_year", "status"],
                        name="warn_school_year_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "ISSUED")),
                        fields=(
                            "school",
                            "student",
                            "academic_year",
                            "warning_type",
                            "level",
                        ),
                        name="uniq_issued_warning_per_scope",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WarningRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("UNEXCUSED_FULL_DAY_ABSENCE", "غياب يوم كامل بدون عذر"),
                            ("MORNING_LATE_OCCURRENCES", "التأخر عن الدوام الصباحي"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("LEVEL_1", "الإنذار الأول"),
                            ("LEVEL_2", "الإنذار الثاني"),
                            ("LEVEL_3", "الإنذار الثالث"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "threshold",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(200),
                        ]
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warning_rules",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "قاعدة إنذار",
                "verbose_name_plural": "قواعد الإنذارات",
                "indexes": [
                    models.Index(
                        fields=["school", "rule_type", "level"],
                        name="warnrule_school_type_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "rule_type", "level"),
                        name="uniq_warning_rule_per_school_type_level",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("threshold__gte", 1), ("threshold__lte", 200)
                        ),
                        name="warning_rule_threshold_range",
                    ),
                ],
            },
        ),
    ]
