# Generated by Django 5.2.17 on 2026-08-20 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0003_schoolsettings_morning_late_grace_minutes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SaaSPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(max_length=40, unique=True, verbose_name="الرمز"),
                ),
                ("name_ar", models.CharField(max_length=100, verbose_name="الاسم")),
                ("name_en", models.CharField(blank=True, default="", max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=1000),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="متاحة")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="معروضة للعامة"),
                ),
                (
                    "billing_period",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "شهري"),
                            ("SEMI_ANNUAL", "نصف سنوي"),
                            ("ANNUAL", "سنوي"),
                            ("CUSTOM", "مخصص"),
                        ],
                        default="ANNUAL",
                        max_length=12,
                    ),
                ),
                (
                    "price_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="SAR", max_length=3)),
                ("trial_days_default", models.PositiveSmallIntegerField(default=30)),
            ],
            options={
                "verbose_name": "باقة",
                "verbose_name_plural": "الباقات",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="SchoolSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRIAL", "تجريبي"),
                            ("ACTIVE", "نشط"),
                            ("GRACE_PERIOD", "مهلة سماح"),
                            ("EXPIRED", "منتهٍ"),
                            ("SUSPENDED", "موقوف"),
                            ("CANCELLED", "ملغى"),
                        ],
                        default="TRIAL",
                        max_length=14,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("trial_started_at", models.DateTimeField(blank=True, null=True)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("grace_ends_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancel_reason",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "suspension_reason",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.saasplan",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="schools.school",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "اشتراك مدرسة",
                "verbose_name_plural": "اشتراكات المدارس",
                "ordering": ["-starts_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("MAX_STUDENTS", "حد الطلاب"),
                            ("MAX_STAFF", "حد الموظفين"),
                            ("MAX_DEVICES", "حد الأجهزة"),
                            ("MAX_STORAGE_GB", "حد التخزين (جيجابايت)"),
                            ("ATTENDANCE", "الحضور"),
                            ("BIOMETRIC_DEVICES", "أجهزة البصمة"),
                            ("ROSTER_SYNC", "مزامنة القوائم"),
                            ("EXCUSES", "الأعذار"),
                            ("WARNINGS", "الإنذارات"),
                            ("DOCUMENTS", "المستندات"),
                            ("REFERRALS", "الإحالات"),
                            ("COUNSELING", "الإرشاد"),
                            ("EXECUTIVE_DASHBOARD", "لوحة الإدارة"),
                        ],
                        max_length=32,
                    ),
                ),
                ("numeric_value", models.IntegerField(blank=True, null=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_override", models.BooleanField(default=False)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlements",
                        to="subscriptions.schoolsubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "استحقاق اشتراك",
                "verbose_name_plural": "استحقاقات الاشتراكات",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CREATED", "إنشاء"),
                            ("TRIAL_STARTED", "بدء تجربة"),
                            ("TRIAL_EXTENDED", "تمديد تجربة"),
                            ("ACTIVATED", "تفعيل"),
                            ("PLAN_CHANGED", "تغيير باقة"),
                            ("EXTENDED", "تمديد"),
                            ("GRACE_STARTED", "بدء مهلة السماح"),
                            ("EXPIRED", "انتهاء"),
                            ("SUSPENDED", "إيقاف"),
                            ("REACTIVATED", "إعادة تفعيل"),
                            ("CANCELLED", "إلغاء"),
                            ("ENTITLEMENT_OVERRIDDEN", "تجاوز استحقاق"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_events",
                        to="schools.school",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="subscriptions.schoolsubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "حدث اشتراك",
                "verbose_name_plural": "أحداث الاشتراكات",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PlanEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("MAX_STUDENTS", "حد الطلاب"),
                            ("MAX_STAFF", "حد الموظفين"),
                            ("MAX_DEVICES", "حد الأجهزة"),
                            ("MAX_STORAGE_GB", "حد التخزين (جيجابايت)"),
                            ("ATTENDANCE", "الحضور"),
                            ("BIOMETRIC_DEVICES", "أجهزة البصمة"),
                            ("ROSTER_SYNC", "مزامنة القوائم"),
                            ("EXCUSES", "الأعذار"),
                            ("WARNINGS", "الإنذارات"),
                            ("DOCUMENTS", "المستندات"),
                            ("REFERRALS", "الإحالات"),
                            ("COUNSELING", "الإرشاد"),
                            ("EXECUTIVE_DASHBOARD", "لوحة الإدارة"),
                        ],
                        max_length=32,
                    ),
                ),
                ("numeric_value", models.IntegerField(blank=True, null=True)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlements",
                        to="subscriptions.saasplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "استحقاق باقة",
                "verbose_name_plural": "استحقاقات الباقات",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan", "key"), name="uniq_entitlement_per_plan"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="schoolsubscription",
            index=models.Index(
                fields=["status", "ends_at"], name="sub_status_ends_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolsubscription",
            index=models.Index(
                fields=["school", "status"], name="sub_school_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolsubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("TRIAL", "ACTIVE", "GRACE_PERIOD"))),
                fields=("school",),
                name="uniq_live_subscription_per_school",
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolsubscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="subscription_ends_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolsubscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "SUSPENDED"), _negated=True),
                    models.Q(
                        ("suspended_at__isnull", False),
                        models.Q(("suspension_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="suspension_requires_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionentitlement",
            constraint=models.UniqueConstraint(
                fields=("subscription", "key"), name="uniq_entitlement_per_subscription"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionevent",
            index=models.Index(
                fields=["school", "-created_at"], name="sub_event_school_idx"
            ),
        ),
    ]
