# Generated by Django 5.2.18 on 2026-10-08 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def enable_rls(apps, schema_editor):
    table = "subscriptions_subscriptionemaildelivery"
    schema_editor.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    schema_editor.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
    guard = ("current_setting('app.rls_bypass', true) = 'on' OR "
             "school_id = NULLIF(current_setting('app.current_school_id', true), '')::bigint")
    schema_editor.execute(f"CREATE POLICY subscription_email_tenant ON {table} "
                          f"USING ({guard}) WITH CHECK ({guard})")
    schema_editor.execute(
        f"CREATE CONSTRAINT TRIGGER same_school_subscription_email AFTER INSERT OR UPDATE ON {table} "
        "DEFERRABLE INITIALLY IMMEDIATE FOR EACH ROW EXECUTE FUNCTION "
        "public.xmansx_enforce_same_school_fk('public', 'subscriptions_schoolsubscription', "
        "'subscription_id')"
    )


def disable_rls(apps, schema_editor):
    table = "subscriptions_subscriptionemaildelivery"
    schema_editor.execute(f"DROP TRIGGER IF EXISTS same_school_subscription_email ON {table}")
    schema_editor.execute(f"DROP POLICY IF EXISTS subscription_email_tenant ON {table}")
    schema_editor.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
    schema_editor.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_enforce_cross_school_foreign_keys'),
        ('schools', '0006_schoolsettings_absence_sms_message_template'),
        ('subscriptions', '0003_schoolsubscription_was_free_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionEmailDelivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deduplication_key', models.CharField(max_length=64, unique=True)),
                ('recipient_hash', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=24)),
                ('snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SENDING', 'SENDING'), ('SUBMITTED_TO_PROVIDER', 'SUBMITTED_TO_PROVIDER'), ('FAILED', 'FAILED'), ('UNKNOWN', 'UNKNOWN'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=24)),
                ('provider_reference', models.CharField(blank=True, max_length=36)),
                ('error_code', models.CharField(blank=True, max_length=48)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.schoolsubscription')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='sub_email_pending_idx')],
            },
        ),
        migrations.RunPython(enable_rls, disable_rls),
    ]
