# Generated by Django 5.2.17 on 2026-10-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_manager_email_outbox"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planentitlement",
            name="key",
            field=models.CharField(
                choices=[
                    ("MAX_STUDENTS", "حد الطلاب"),
                    ("MAX_STAFF", "حد الموظفين"),
                    ("MAX_DEVICES", "حد الأجهزة"),
                    ("MAX_STORAGE_GB", "حد التخزين (جيجابايت)"),
                    ("ATTENDANCE", "الحضور"),
                    ("BIOMETRIC_DEVICES", "أجهزة البصمة"),
                    ("ABSENCE_SMS", "رسائل الغياب"),
                    ("PARENT_PORTAL", "بوابة ولي الأمر"),
                    ("ROSTER_SYNC", "مزامنة القوائم"),
                    ("EXCUSES", "الأعذار"),
                    ("WARNINGS", "الإنذارات"),
                    ("DOCUMENTS", "المستندات"),
                    ("REFERRALS", "الإحالات"),
                    ("COUNSELING", "الإرشاد"),
                    ("EXECUTIVE_DASHBOARD", "لوحة الإدارة"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionentitlement",
            name="key",
            field=models.CharField(
                choices=[
                    ("MAX_STUDENTS", "حد الطلاب"),
                    ("MAX_STAFF", "حد الموظفين"),
                    ("MAX_DEVICES", "حد الأجهزة"),
                    ("MAX_STORAGE_GB", "حد التخزين (جيجابايت)"),
                    ("ATTENDANCE", "الحضور"),
                    ("BIOMETRIC_DEVICES", "أجهزة البصمة"),
                    ("ABSENCE_SMS", "رسائل الغياب"),
                    ("PARENT_PORTAL", "بوابة ولي الأمر"),
                    ("ROSTER_SYNC", "مزامنة القوائم"),
                    ("EXCUSES", "الأعذار"),
                    ("WARNINGS", "الإنذارات"),
                    ("DOCUMENTS", "المستندات"),
                    ("REFERRALS", "الإحالات"),
                    ("COUNSELING", "الإرشاد"),
                    ("EXECUTIVE_DASHBOARD", "لوحة الإدارة"),
                ],
                max_length=32,
            ),
        ),
    ]
