# Generated by Django 5.2.17 on 2026-08-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackupRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("DATABASE", "Database"),
                            ("PRIVATE_OBJECTS", "Private objects"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("checksum", models.CharField(blank=True, default="", max_length=64)),
                (
                    "storage_reference",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("duration_ms", models.PositiveBigIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["backup_type", "status", "-finished_at"],
                        name="backup_type_status_idx",
                    )
                ],
            },
        ),
    ]
