# Generated by Django 5.2.17 on 2026-08-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="اسم المدرسة")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="المعرف"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشطة"),
                            ("SUSPENDED", "موقوفة"),
                            ("ARCHIVED", "مؤرشفة"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مدرسة",
                "verbose_name_plural": "المدارس",
                "indexes": [models.Index(fields=["status"], name="school_status_idx")],
            },
        ),
    ]
