# Generated by Django 5.2.17 on 2026-08-18 15:00

import django.core.validators
import django.db.models.deletion
import schools.settings_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ministry_school_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="الرقم الوزاري",
                    ),
                ),
                (
                    "education_stage",
                    models.CharField(
                        choices=[
                            ("ELEMENTARY", "ابتدائي"),
                            ("MIDDLE", "متوسط"),
                            ("SECONDARY", "ثانوي"),
                            ("MULTI_STAGE", "متعدد المراحل"),
                        ],
                        default="SECONDARY",
                        max_length=20,
                        verbose_name="المرحلة التعليمية",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="المدينة"
                    ),
                ),
                (
                    "official_principal_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="اسم المدير الرسمي (للطباعة)",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=schools.settings_models.school_logo_path,
                    ),
                ),
                ("timezone", models.CharField(default="Asia/Riyadh", max_length=50)),
                (
                    "attendance_edit_window_minutes",
                    models.PositiveSmallIntegerField(
                        default=15,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="مهلة تعديل التحضير (دقائق)",
                    ),
                ),
                (
                    "unprepared_period_alert_minutes",
                    models.PositiveSmallIntegerField(
                        default=25,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="تنبيه عدم التحضير بعد (دقائق)",
                    ),
                ),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات مدرسة",
                "verbose_name_plural": "إعدادات المدارس",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("attendance_edit_window_minutes__lte", 120)
                        ),
                        name="settings_edit_window_max",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("unprepared_period_alert_minutes__gte", 1),
                            ("unprepared_period_alert_minutes__lte", 120),
                        ),
                        name="settings_alert_minutes_range",
                    ),
                ],
            },
        ),
    ]
