# Generated by Django 5.2.17 on 2026-08-19 11:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_schoolsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="morning_late_grace_minutes",
            field=models.PositiveSmallIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(120),
                ],
                verbose_name="فترة السماح الصباحية (دقائق)",
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="school_day_start_time",
            field=models.TimeField(
                default=datetime.time(7, 0), verbose_name="بداية الدوام الصباحي"
            ),
        ),
    ]
