# Generated by Django 5.2 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_schoolsettings_morning_late_grace_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="school_type",
            field=models.CharField(
                choices=[("BOYS", "بنين"), ("GIRLS", "بنات")],
                default="BOYS",
                max_length=10,
                verbose_name="نوع المدرسة",
            ),
        ),
    ]
