# Generated by Django 5.2.17 on 2026-09-29 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_school_school_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="absence_sms_min_approved_periods",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ],
                verbose_name="عدد التحاضير المعتمدة قبل إرسال الغياب",
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("absence_sms_min_approved_periods__lte", 20)),
                name="settings_absence_sms_periods_max",
            ),
        ),
    ]
