# Generated by Django 5.2.17 on 2026-09-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0005_schoolsettings_absence_sms_min_approved_periods_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="absence_sms_message_template",
            field=models.CharField(
                default="ولي الأمر، تم تسجيل غياب الطالب «اسم الطالب» يوم «التاريخ». يرجى تقديم العذر للمدرسة إن وجد.",
                max_length=500,
                verbose_name="قالب رسالة الغياب الكامل",
            ),
        ),
    ]
