# Generated by Django 5.2.17 on 2026-08-18 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "فعالة"),
                            ("INVITED", "مدعو"),
                            ("SUSPENDED", "موقوفة"),
                            ("LEFT", "منتهية"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="schools.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "عضوية مدرسية",
                "verbose_name_plural": "العضويات المدرسية",
            },
        ),
        migrations.CreateModel(
            name="SchoolMembershipRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SCHOOL_MANAGER", "مدير المدرسة"),
                            ("VICE_PRINCIPAL", "الوكيل"),
                            ("COUNSELOR", "المرشد الطلابي"),
                            ("TEACHER", "معلم"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="memberships.schoolmembership",
                    ),
                ),
            ],
            options={
                "verbose_name": "دور العضوية",
                "verbose_name_plural": "أدوار العضويات",
            },
        ),
        migrations.AddIndex(
            model_name="schoolmembership",
            index=models.Index(
                fields=["school", "status"], name="membership_school_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "school"), name="uniq_membership_user_school"
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolmembershiprole",
            constraint=models.UniqueConstraint(
                fields=("membership", "role"), name="uniq_membership_role"
            ),
        ),
    ]
