# Generated by Django 5.2.17 on 2026-08-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolmembership",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "فعالة"),
                    ("INVITED", "مدعو"),
                    ("DECLINED", "مرفوضة"),
                    ("SUSPENDED", "موقوفة"),
                    ("LEFT", "منتهية"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
