# Generated by Django 5.2 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memberships", "0002_alter_schoolmembership_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolmembershiprole",
            name="role",
            field=models.CharField(
                choices=[
                    ("SCHOOL_MANAGER", "مدير المدرسة"),
                    ("VICE_PRINCIPAL", "الوكيل"),
                    ("COUNSELOR", "المرشد الطلابي"),
                    ("TEACHER", "معلم"),
                    ("GATE_GUARD", "حارس البوابة"),
                ],
                max_length=30,
            ),
        ),
    ]
