# Generated by Django 5.2.17 on 2026-08-18 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0002_schoolsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, verbose_name="اسم العام")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPCOMING", "قادم"),
                            ("ACTIVE", "نشط"),
                            ("CLOSED", "منتهي"),
                            ("ARCHIVED", "مؤرشف"),
                        ],
                        default="UPCOMING",
                        max_length=20,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_years",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "عام دراسي",
                "verbose_name_plural": "الأعوام الدراسية",
            },
        ),
        migrations.CreateModel(
            name="BellSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="اسم الجدول")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشط"),
                            ("INACTIVE", "غير نشط"),
                            ("ARCHIVED", "مؤرشف"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bell_schedules",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "جدول حصص",
                "verbose_name_plural": "جداول الحصص",
            },
        ),
        migrations.CreateModel(
            name="BellPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=50, verbose_name="اسم الحصة")),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_attendance_period", models.BooleanField(default=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bell_periods",
                        to="schools.school",
                    ),
                ),
                (
                    "bell_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="academics.bellschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "حصة",
                "verbose_name_plural": "الحصص",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="SchoolWeekDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "الأحد"),
                            (1, "الاثنين"),
                            (2, "الثلاثاء"),
                            (3, "الأربعاء"),
                            (4, "الخميس"),
                            (5, "الجمعة"),
                            (6, "السبت"),
                        ]
                    ),
                ),
                ("is_school_day", models.BooleanField(default=False)),
                (
                    "bell_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_days",
                        to="academics.bellschedule",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="week_days",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "يوم دراسي",
                "verbose_name_plural": "أيام الدراسة",
                "ordering": ["weekday"],
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, verbose_name="اسم الفصل")),
                ("sequence", models.PositiveSmallIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPCOMING", "قادم"),
                            ("ACTIVE", "نشط"),
                            ("CLOSED", "منتهي"),
                        ],
                        default="UPCOMING",
                        max_length=20,
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "فصل دراسي",
                "verbose_name_plural": "الفصول الدراسية",
                "ordering": ["sequence"],
            },
        ),
        migrations.AddIndex(
            model_name="academicyear",
            index=models.Index(
                fields=["school", "status"], name="year_school_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="academicyear",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("school",),
                name="uniq_active_year_per_school",
            ),
        ),
        migrations.AddConstraint(
            model_name="academicyear",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_date__lt", models.F("end_date"))),
                name="year_start_before_end",
            ),
        ),
        migrations.AddIndex(
            model_name="bellschedule",
            index=models.Index(
                fields=["school", "status"], name="bell_school_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bellperiod",
            constraint=models.UniqueConstraint(
                fields=("bell_schedule", "sequence"),
                name="uniq_period_sequence_per_schedule",
            ),
        ),
        migrations.AddConstraint(
            model_name="bellperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="period_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolweekday",
            constraint=models.UniqueConstraint(
                fields=("school", "weekday"), name="uniq_school_weekday"
            ),
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.UniqueConstraint(
                fields=("academic_year", "sequence"),
                name="uniq_semester_sequence_per_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("school",),
                name="uniq_active_semester_per_school",
            ),
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_date__lte", models.F("end_date"))),
                name="semester_start_before_end",
            ),
        ),
    ]
