# Generated by Django 5.2.17 on 2026-10-06 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("schools", "0006_schoolsettings_absence_sms_message_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinistryCalendarSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                ("documents", models.JSONField(default=list)),
                ("calendars", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="academicyear",
            name="ministry_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="academic_years",
                to="academics.ministrycalendarsnapshot",
            ),
        ),
        migrations.CreateModel(
            name="MinistryCalendarSync",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        default="NATIONAL",
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("checked_at", models.DateTimeField(null=True)),
                ("succeeded_at", models.DateTimeField(null=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=80)),
                (
                    "snapshot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="academics.ministrycalendarsnapshot",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SchoolCalendarPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.CharField(
                        choices=[
                            ("UNCONFIRMED", "لم يُحدد نطاق التقويم"),
                            ("NATIONAL", "التقويم الوطني للمدارس الحكومية"),
                            ("EXCEPTION", "تقويم خاص أو محلي معتمد"),
                        ],
                        default="UNCONFIRMED",
                        max_length=20,
                    ),
                ),
                (
                    "scope_note",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("checked_at", models.DateTimeField(null=True)),
                ("outcome", models.CharField(blank=True, default="", max_length=80)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.school"
                    ),
                ),
            ],
            options={
                "verbose_name": "نطاق تقويم المدرسة",
                "verbose_name_plural": "نطاقات تقويم المدارس",
            },
        ),
    ]
