# Generated by Django 5.2.17 on 2026-08-19 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("memberships", "0002_alter_schoolmembership_status"),
        ("schools", "0003_schoolsettings_morning_late_grace_minutes_and_more"),
        ("students", "0003_section_qr_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="اسم الجهاز")),
                (
                    "vendor",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="الشركة"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="الموديل"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("connection_type", models.CharField(default="TCP", max_length=20)),
                (
                    "local_ip",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=45,
                        verbose_name="عنوان IP المحلي",
                    ),
                ),
                ("local_port", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "connection_secret_encrypted",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "متصل"),
                            ("OFFLINE", "غير متصل"),
                            ("DEGRADED", "متقطع"),
                            ("DISABLED", "موقوف"),
                            ("UNKNOWN", "غير معروف"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_successful_sync_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("test_requested_at", models.DateTimeField(blank=True, null=True)),
                ("test_result", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_devices",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "جهاز حضور",
                "verbose_name_plural": "أجهزة الحضور",
            },
        ),
        migrations.CreateModel(
            name="DeviceBridgeInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "installation_name",
                    models.CharField(max_length=100, verbose_name="اسم التثبيت"),
                ),
                (
                    "installation_identifier",
                    models.CharField(max_length=32, unique=True),
                ),
                ("credential_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "فعال"), ("DISABLED", "موقوف")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_bridges",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "جسر أجهزة",
                "verbose_name_plural": "جسور الأجهزة",
            },
        ),
        migrations.CreateModel(
            name="DeviceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_event_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("dedupe_key", models.CharField(max_length=128)),
                ("external_user_id", models.CharField(max_length=64)),
                ("occurred_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("FINGERPRINT", "بصمة إصبع"),
                            ("FACE", "وجه"),
                            ("CARD", "بطاقة"),
                            ("PIN", "رقم سري"),
                            ("OTHER", "أخرى"),
                            ("UNKNOWN", "غير معروف"),
                        ],
                        default="UNKNOWN",
                        max_length=15,
                    ),
                ),
                ("event_type", models.CharField(default="CHECK_IN", max_length=20)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("PROCESSED", "معالج"),
                            ("UNMATCHED", "غير مطابق"),
                            ("IGNORED", "متجاهل"),
                        ],
                        default="UNMATCHED",
                        max_length=10,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="devices.attendancedevice",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_events",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device_events",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "حدث جهاز",
                "verbose_name_plural": "أحداث الأجهزة",
            },
        ),
        migrations.CreateModel(
            name="SchoolArrival",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attendance_date", models.DateField()),
                ("first_arrival_at", models.DateTimeField()),
                ("raw_late_minutes", models.PositiveIntegerField(default=0)),
                ("counted_late_minutes", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("ON_TIME", "في الوقت"), ("LATE", "متأخر")],
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("BIOMETRIC", "جهاز"), ("MANUAL", "يدوي")],
                        max_length=10,
                    ),
                ),
                (
                    "device_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="devices.deviceevent",
                    ),
                ),
                (
                    "recorded_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="memberships.schoolmembership",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_arrivals",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="school_arrivals",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "وصول صباحي",
                "verbose_name_plural": "الوصول الصباحي",
            },
        ),
        migrations.CreateModel(
            name="SchoolArrivalChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_arrival_time", models.DateTimeField()),
                ("new_arrival_time", models.DateTimeField()),
                ("previous_status", models.CharField(max_length=10)),
                ("new_status", models.CharField(max_length=10)),
                ("previous_counted_late_minutes", models.PositiveIntegerField()),
                ("new_counted_late_minutes", models.PositiveIntegerField()),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="memberships.schoolmembership",
                    ),
                ),
                (
                    "arrival",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="devices.schoolarrival",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrival_changes",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعديل وصول",
                "verbose_name_plural": "تعديلات الوصول",
            },
        ),
        migrations.CreateModel(
            name="StudentDeviceIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_user_id", models.CharField(max_length=64)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("MATCHED", "مطابق"),
                            ("UNMATCHED", "غير مطابق"),
                            ("CONFLICT", "متعارض"),
                            ("IGNORED", "متجاهل"),
                        ],
                        default="UNMATCHED",
                        max_length=10,
                    ),
                ),
                ("mapped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identities",
                        to="devices.attendancedevice",
                    ),
                ),
                (
                    "mapped_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="memberships.schoolmembership",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_identities",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device_identities",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "هوية مستخدم جهاز",
                "verbose_name_plural": "هويات مستخدمي الأجهزة",
            },
        ),
        migrations.AddIndex(
            model_name="deviceevent",
            index=models.Index(
                fields=["school", "occurred_at"], name="devevent_school_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deviceevent",
            index=models.Index(
                fields=["device", "processing_status"],
                name="devevent_device_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="deviceevent",
            constraint=models.UniqueConstraint(
                fields=("device", "dedupe_key"), name="uniq_event_per_device_key"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolarrival",
            index=models.Index(
                fields=["school", "attendance_date", "status"],
                name="arrival_school_date_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolarrival",
            constraint=models.UniqueConstraint(
                fields=("school", "student", "attendance_date"),
                name="uniq_arrival_per_student_date",
            ),
        ),
        migrations.AddIndex(
            model_name="studentdeviceidentity",
            index=models.Index(
                fields=["school", "student"], name="identity_school_student_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentdeviceidentity",
            constraint=models.UniqueConstraint(
                fields=("device", "external_user_id"),
                name="uniq_identity_per_device_external_id",
            ),
        ),
    ]
