# Generated by Django 5.2.17 on 2026-08-19 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("devices", "0001_initial"),
        ("memberships", "0002_alter_schoolmembership_status"),
        ("schools", "0003_schoolsettings_morning_late_grace_minutes_and_more"),
        ("students", "0003_section_qr_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceRosterSyncJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ANALYZING", "جارٍ الفحص"),
                            ("READY_FOR_REVIEW", "جاهز للمراجعة"),
                            ("APPROVED", "معتمد"),
                            ("RUNNING", "قيد التنفيذ"),
                            ("COMPLETED", "مكتمل"),
                            ("PARTIALLY_FAILED", "مكتمل جزئياً"),
                            ("FAILED", "فشل"),
                            ("CANCELLED", "ملغى"),
                            ("STALE", "قديم"),
                        ],
                        default="ANALYZING",
                        max_length=24,
                    ),
                ),
                (
                    "roster_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "device_roster_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("matched_count", models.PositiveIntegerField(default=0)),
                ("create_count", models.PositiveIntegerField(default=0)),
                ("update_count", models.PositiveIntegerField(default=0)),
                ("delete_count", models.PositiveIntegerField(default=0)),
                ("conflict_count", models.PositiveIntegerField(default=0)),
                ("read_requested_at", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device_roster_sync_jobs",
                        to="memberships.schoolmembership",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_sync_jobs",
                        to="devices.attendancedevice",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_roster_sync_jobs",
                        to="schools.school",
                    ),
                ),
                (
                    "source_academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device_roster_sync_jobs",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "source_student_import",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_roster_sync_jobs",
                        to="students.studentimportjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceRosterSyncItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_user_id", models.CharField(max_length=64)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("MATCHED", "مطابق"),
                            ("CREATE", "إضافة"),
                            ("UPDATE", "تحديث"),
                            ("DELETE", "إزالة"),
                            ("CONFLICT", "تعارض"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "بانتظار التنفيذ"),
                            ("RUNNING", "قيد التنفيذ"),
                            ("SUCCEEDED", "ناجح"),
                            ("FAILED_RETRYABLE", "فشل قابل للإعادة"),
                            ("FAILED_FINAL", "فشل نهائي"),
                            ("SKIPPED", "متجاوز"),
                        ],
                        default="PENDING",
                        max_length=24,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                ("error_code", models.CharField(blank=True, default="", max_length=80)),
                ("safe_before_snapshot", models.JSONField(blank=True, default=dict)),
                ("safe_after_snapshot", models.JSONField(blank=True, default=dict)),
                ("command_id", models.CharField(blank=True, default="", max_length=64)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_sync_items",
                        to="devices.attendancedevice",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device_roster_sync_items",
                        to="students.student",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="devices.devicerostersyncjob",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="devicerostersyncjob",
            index=models.Index(
                fields=["school", "device", "status"],
                name="roster_job_school_device_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="devicerostersyncitem",
            index=models.Index(
                fields=["job", "action", "status"], name="roster_item_job_action_idx"
            ),
        ),
    ]
