# Generated by Django 5.2.17 on 2026-08-19 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("memberships", "0002_alter_schoolmembership_status"),
        ("schools", "0002_schoolsettings"),
        ("students", "0003_section_qr_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attendance_date", models.DateField()),
                ("period_sequence", models.PositiveSmallIntegerField()),
                ("bell_period_snapshot", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "قيد التحضير"),
                            ("SUBMITTED", "معتمد"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("roster_fingerprint", models.CharField(max_length=64)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_sessions",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "bell_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_sessions",
                        to="academics.bellperiod",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="schools.school",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_sessions",
                        to="students.section",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_sessions",
                        to="academics.semester",
                    ),
                ),
                (
                    "started_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="started_attendance_sessions",
                        to="memberships.schoolmembership",
                    ),
                ),
                (
                    "submitted_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_attendance_sessions",
                        to="memberships.schoolmembership",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسة تحضير",
                "verbose_name_plural": "جلسات التحضير",
            },
        ),
        migrations.CreateModel(
            name="AttendanceMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ABSENT", "غائب"), ("LATE", "متأخر")], max_length=10
                    ),
                ),
                ("arrival_time", models.TimeField(blank=True, null=True)),
                (
                    "late_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_marks",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_marks",
                        to="students.student",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="attendance.attendancesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "علامة حضور",
                "verbose_name_plural": "علامات الحضور",
            },
        ),
        migrations.CreateModel(
            name="AttendanceChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_status", models.CharField(max_length=10)),
                ("new_status", models.CharField(max_length=10)),
                (
                    "previous_late_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "new_late_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="memberships.schoolmembership",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_changes",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_changes",
                        to="students.student",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="attendance.attendancesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعديل حضور",
                "verbose_name_plural": "تعديلات الحضور",
            },
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["school", "attendance_date", "period_sequence", "status"],
                name="att_school_date_period_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["school", "section", "attendance_date"],
                name="att_school_section_date_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancesession",
            constraint=models.UniqueConstraint(
                fields=("school", "section", "attendance_date", "period_sequence"),
                name="uniq_session_per_section_date_period",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancemark",
            index=models.Index(
                fields=["school", "student"], name="mark_school_student_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancemark",
            index=models.Index(
                fields=["school", "status"], name="mark_school_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancemark",
            constraint=models.UniqueConstraint(
                fields=("session", "student"), name="uniq_mark_per_session_student"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancechange",
            index=models.Index(
                fields=["school", "session"], name="attchange_school_session_idx"
            ),
        ),
    ]
