# Generated by Django 5.2.17 on 2026-08-19 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("attendance", "0002_alert_minutes_snapshot"),
        ("schools", "0002_schoolsettings"),
        ("students", "0003_section_qr_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceDayContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attendance_date", models.DateField()),
                ("schedule_snapshot", models.JSONField()),
                ("timezone_snapshot", models.CharField(max_length=50)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_day_contexts",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_day_contexts",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "سياق يوم الحضور",
                "verbose_name_plural": "سياقات أيام الحضور",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "attendance_date"),
                        name="uniq_day_context_per_school_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyAttendanceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attendance_date", models.DateField()),
                ("expected_periods", models.PositiveSmallIntegerField()),
                ("submitted_periods", models.PositiveSmallIntegerField()),
                ("absent_periods", models.PositiveSmallIntegerField()),
                ("late_periods", models.PositiveSmallIntegerField()),
                ("present_periods", models.PositiveSmallIntegerField()),
                ("total_late_minutes", models.PositiveIntegerField(default=0)),
                (
                    "completeness_status",
                    models.CharField(
                        choices=[("COMPLETE", "مكتمل"), ("INCOMPLETE", "غير مكتمل")],
                        max_length=12,
                    ),
                ),
                (
                    "absence_status",
                    models.CharField(
                        choices=[
                            ("UNDETERMINED", "غير محسوم"),
                            ("NONE", "لا غياب"),
                            ("PARTIAL", "غياب جزئي"),
                            ("FULL", "غياب يوم كامل"),
                        ],
                        max_length=14,
                    ),
                ),
                ("calculated_at", models.DateTimeField()),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_attendance_summaries",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_attendance_summaries",
                        to="schools.school",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_attendance_summaries",
                        to="students.section",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_attendance_summaries",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملخص حضور يومي",
                "verbose_name_plural": "ملخصات الحضور اليومية",
                "indexes": [
                    models.Index(
                        fields=["school", "attendance_date", "absence_status"],
                        name="daily_school_date_status_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "student", "attendance_date"),
                        name="uniq_daily_summary_per_student_date",
                    )
                ],
            },
        ),
    ]
