# Generated by Django 5.2.17 on 2026-08-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_backfill_day_contexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendancesummary',
            name='excused_absent_periods',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyattendancesummary',
            name='unexcused_absent_periods',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
