# Generated by Django 5.2.17 on 2026-08-19 13:29

import django.db.models.deletion
import excuses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0005_dailyattendancesummary_excused_absent_periods_and_more'),
        ('memberships', '0002_alter_schoolmembership_status'),
        ('schools', '0003_schoolsettings_morning_late_grace_minutes_and_more'),
        ('students', '0003_section_qr_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceExcuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'بانتظار الاعتماد'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض'), ('CANCELLED', 'ملغى')], default='PENDING', max_length=10)),
                ('reason_type', models.CharField(choices=[('MEDICAL_REPORT', 'تقرير طبي'), ('MEDICAL_APPOINTMENT', 'موعد طبي'), ('OFFICIAL', 'عذر رسمي'), ('FAMILY', 'ظرف أسري'), ('OTHER', 'أخرى')], max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('recorded_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=300)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=300)),
                ('approved_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='memberships.schoolmembership')),
                ('cancelled_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='memberships.schoolmembership')),
                ('recorded_by_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='memberships.schoolmembership')),
                ('rejected_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='memberships.schoolmembership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_excuses', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absence_excuses', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='AbsenceExcuseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=excuses.models.excuse_attachment_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=50)),
                ('size_bytes', models.PositiveIntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('excuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='excuses.absenceexcuse')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('uploaded_by_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='memberships.schoolmembership')),
            ],
        ),
        migrations.CreateModel(
            name='AbsenceExcuseCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_date', models.DateField()),
                ('period_sequence_snapshot', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'نشطة'), ('VOIDED', 'ملغاة')], default='ACTIVE', max_length=10)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, default='', max_length=50)),
                ('attendance_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='attendance.attendancesession')),
                ('excuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='excuses.absenceexcuse')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excuse_coverages', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='AbsenceExcuseTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_date', models.DateField()),
                ('period_sequence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('excuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='excuses.absenceexcuse')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school')),
            ],
        ),
        migrations.AddIndex(
            model_name='absenceexcuse',
            index=models.Index(fields=['school', 'student', 'status'], name='excuse_school_student_idx'),
        ),
        migrations.AddIndex(
            model_name='absenceexcuse',
            index=models.Index(fields=['school', 'status'], name='excuse_school_status_idx'),
        ),
        migrations.AddIndex(
            model_name='absenceexcuseattachment',
            index=models.Index(fields=['school', 'excuse'], name='excuse_attach_school_idx'),
        ),
        migrations.AddIndex(
            model_name='absenceexcusecoverage',
            index=models.Index(fields=['student', 'attendance_date', 'status'], name='coverage_student_date_idx'),
        ),
        migrations.AddIndex(
            model_name='absenceexcusecoverage',
            index=models.Index(fields=['school', 'attendance_date', 'status'], name='coverage_school_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='absenceexcusecoverage',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('attendance_session', 'student'), name='uniq_active_coverage_per_absence'),
        ),
        migrations.AddIndex(
            model_name='absenceexcusetarget',
            index=models.Index(fields=['school', 'attendance_date'], name='excuse_target_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='absenceexcusetarget',
            constraint=models.UniqueConstraint(fields=('excuse', 'attendance_date', 'period_sequence'), name='uniq_excuse_target', nulls_distinct=False),
        ),
    ]
