# Generated by Django 5.2.17 on 2026-10-07 23:13

import django.db.models.deletion
import documents.storage
import parents.request_models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0007_remove_period_lateness"),
        ("counseling", "0002_remove_period_lateness"),
        ("documents", "0004_remove_period_lateness_documents"),
        ("excuses", "0001_initial"),
        ("memberships", "0004_schoolmembershipcapability"),
        ("schools", "0006_schoolsettings_absence_sms_message_template"),
        ("student_warnings", "0003_remove_period_lateness_snapshots"),
        ("students", "0007_guardian_contact_revision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("body", models.TextField(blank=True, default="", max_length=4000)),
                (
                    "required_action",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revocation_reason",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="family_publications",
                        to="counseling.counselorcase",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="family_publications",
                        to="documents.generateddocument",
                    ),
                ),
                (
                    "published_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="memberships.schoolmembership",
                    ),
                ),
                (
                    "revoked_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="memberships.schoolmembership",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="family_publications",
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GlobalMobileChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("new_mobile_encrypted", models.TextField()),
                ("new_mobile_hash", models.CharField(max_length=64)),
                ("verification_note", models.CharField(max_length=600)),
                ("reason", models.CharField(max_length=300)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.school"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="students.student",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GuardianContactReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("previous_revision", models.PositiveIntegerField()),
                ("current_revision", models.PositiveIntegerField()),
                ("source", models.CharField(default="DATABASE", max_length=40)),
                ("reason", models.CharField(blank=True, max_length=300)),
                ("previous_mobile_hash", models.CharField(blank=True, max_length=64)),
                ("current_mobile_hash", models.CharField(blank=True, max_length=64)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("verification_note", models.CharField(blank=True, max_length=600)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.school"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuardianRegistrationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("mobile_encrypted", models.TextField()),
                ("mobile_hash", models.CharField(max_length=64)),
                ("mobile_masked", models.CharField(max_length=20)),
                ("identifier_encrypted", models.TextField()),
                ("identifier_hash", models.CharField(max_length=64)),
                ("receipt_hash", models.CharField(max_length=64, unique=True)),
                (
                    "relationship_type",
                    models.CharField(default="ولي أمر", max_length=60),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "قيد المراجعة"),
                            ("NEEDS_INFO", "تحتاج استكمالاً"),
                            ("APPROVED", "معتمدة بانتظار التفعيل"),
                            ("REJECTED", "مرفوضة"),
                            ("ACTIVATED", "تم التفعيل"),
                            ("CANCELLED", "ملغاة"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("contact_revision", models.PositiveIntegerField(default=1)),
                ("contact_bound", models.BooleanField(default=True)),
                ("approved_contact_hash", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("verification_note", models.CharField(blank=True, max_length=600)),
                ("decision_reason", models.CharField(blank=True, max_length=300)),
                ("applicant_note", models.CharField(blank=True, max_length=600)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.school"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuardianActivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("contact_revision", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_status", models.CharField(default="PENDING", max_length=12)),
                ("failure_code", models.CharField(blank=True, max_length=60)),
                ("provider_reference", models.CharField(blank=True, max_length=100)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.school"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="students.student",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activations",
                        to="parents.guardianregistrationrequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GuardianStudentRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_type",
                    models.CharField(default="ولي أمر", max_length=60),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "بانتظار الاعتماد"),
                            ("ACTIVE", "نشطة"),
                            ("SUSPENDED_CONTACT_REVIEW", "معلقة للمراجعة"),
                            ("REJECTED", "مرفوضة"),
                            ("REVOKED", "مسحوبة"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_revision", models.PositiveIntegerField(default=1)),
                ("contact_bound", models.BooleanField(default=True)),
                ("contact_revision", models.PositiveIntegerField(default=1)),
                ("approved_contact_hash", models.CharField(blank=True, max_length=64)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("suspension_reason", models.CharField(blank=True, max_length=300)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("verification_note", models.CharField(blank=True, max_length=600)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.school"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="students.student",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guardian_relations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FamilyPublicationAcknowledgement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("acknowledged_at", models.DateTimeField()),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgements",
                        to="parents.familypublication",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="schools.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_acknowledgements",
                        to="parents.guardianstudentrelation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceCorrectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "بانتظار المراجعة"),
                            ("NEEDS_INFO", "يحتاج استكمالاً"),
                            ("APPROVED", "معتمد"),
                            ("REJECTED", "مرفوض"),
                            ("CANCELLED", "ملغى"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision_note",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parent_correction_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="memberships.schoolmembership",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="schools.school",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parent_correction_requests",
                        to="attendance.attendancesession",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parent_correction_requests",
                        to="students.student",
                    ),
                ),
                (
                    "relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correction_requests",
                        to="parents.guardianstudentrelation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParentExcuseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "بانتظار المراجعة"),
                            ("NEEDS_INFO", "يحتاج استكمالاً"),
                            ("APPROVED", "معتمد"),
                            ("REJECTED", "مرفوض"),
                            ("CANCELLED", "ملغى"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                (
                    "reason_type",
                    models.CharField(
                        choices=[
                            ("MEDICAL_REPORT", "تقرير طبي"),
                            ("MEDICAL_APPOINTMENT", "موعد طبي"),
                            ("OFFICIAL", "عذر رسمي"),
                            ("FAMILY", "ظرف أسري"),
                            ("OTHER", "أخرى"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=500)),
                ("targets", models.JSONField(default=list)),
                ("target_fingerprint", models.CharField(max_length=64)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision_note",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "administrative_excuse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parent_requests",
                        to="excuses.absenceexcuse",
                    ),
                ),
                (
                    "relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="excuse_requests",
                        to="parents.guardianstudentrelation",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parent_excuse_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="memberships.schoolmembership",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parent_excuse_requests",
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParentExcuseAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        storage=documents.storage.PrivateDocumentStorage,
                        upload_to=parents.request_models.parent_attachment_path,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=50)),
                ("size_bytes", models.PositiveIntegerField()),
                ("checksum", models.CharField(max_length=64)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="schools.school",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="parents.parentexcuserequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ParentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(max_length=32)),
                ("dedup_key", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=180)),
                ("body", models.CharField(blank=True, default="", max_length=500)),
                ("requires_action", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("action_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="parents.guardianstudentrelation",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="schools.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParentRegistrationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.school"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecipientContactBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mobile_hash", models.CharField(max_length=64)),
                ("reason", models.CharField(max_length=300)),
                ("verification_note", models.CharField(max_length=600)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.school"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WarningAcknowledgement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("acknowledged_at", models.DateTimeField()),
                (
                    "relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warning_acknowledgements",
                        to="parents.guardianstudentrelation",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="schools.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_acknowledgements",
                        to="student_warnings.studentwarning",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="familypublication",
            index=models.Index(
                fields=["school", "student", "published_at"],
                name="family_publication_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="guardiancontactreview",
            index=models.Index(
                fields=["school", "resolved_at"], name="parent_contact_review_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guardianregistrationrequest",
            index=models.Index(
                fields=["school", "status", "created_at"], name="parent_reg_queue_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="guardianregistrationrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["PENDING", "NEEDS_INFO", "APPROVED"])
                ),
                fields=("school", "mobile_hash", "identifier_hash"),
                name="uniq_open_guardian_registration",
            ),
        ),
        migrations.AddIndex(
            model_name="guardianstudentrelation",
            index=models.Index(
                fields=["user", "status"], name="parent_user_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guardianstudentrelation",
            index=models.Index(
                fields=["school", "status"], name="parent_school_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="guardianstudentrelation",
            constraint=models.UniqueConstraint(
                fields=("user", "student"), name="uniq_guardian_student"
            ),
        ),
        migrations.AddConstraint(
            model_name="familypublicationacknowledgement",
            constraint=models.UniqueConstraint(
                fields=("relation", "publication"), name="uniq_parent_publication_ack"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancecorrectionrequest",
            index=models.Index(
                fields=["school", "status", "created_at"],
                name="parent_correct_queue_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancecorrectionrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PENDING", "NEEDS_INFO"])),
                fields=("student", "session"),
                name="uniq_open_parent_correction",
            ),
        ),
        migrations.AddIndex(
            model_name="parentexcuserequest",
            index=models.Index(
                fields=["school", "status", "created_at"],
                name="parent_excuse_queue_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="parentexcuserequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PENDING", "NEEDS_INFO"])),
                fields=("relation", "target_fingerprint"),
                name="uniq_open_parent_excuse",
            ),
        ),
        migrations.AddIndex(
            model_name="parentnotification",
            index=models.Index(
                fields=["user", "-created_at"], name="parent_notification_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="parentnotification",
            constraint=models.UniqueConstraint(
                fields=("relation", "dedup_key"), name="uniq_parent_notification"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipientcontactblock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("resolved_at__isnull", True)),
                fields=("student", "mobile_hash"),
                name="uniq_open_recipient_block",
            ),
        ),
        migrations.AddConstraint(
            model_name="warningacknowledgement",
            constraint=models.UniqueConstraint(
                fields=("relation", "warning"), name="uniq_parent_warning_ack"
            ),
        ),
    ]
