# Generated by Django 5.2.18 on 2026-10-08 05:19
# ruff: noqa: S608

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# These policies deliberately do not trust the general platform rls_bypass GUC.
# The database owner provisions reviewer grants; the application cannot grant itself
# either review responsibility. All functions retain invoker privileges.
GUARD_SQL = r"""
CREATE FUNCTION public.xmansx_recovery_review_stage() RETURNS text
LANGUAGE sql STABLE SET search_path = pg_catalog AS $$
 SELECT a.stage FROM public.parents_recoveryreviewauthorization a
 JOIN public.platform_team_platformstaffmembership p ON p.user_id = a.reviewer_id
 JOIN public.accounts_user u ON u.id = a.reviewer_id
 WHERE a.reviewer_id = NULLIF(current_setting('app.current_user_id', true), '')::bigint
   AND a.revoked_at IS NULL AND a.expires_at > statement_timestamp()
   AND p.status = 'ACTIVE' AND u.is_active AND NOT u.must_change_password
$$;

CREATE FUNCTION public.xmansx_recovery_school_intake(target_school bigint) RETURNS boolean
LANGUAGE sql STABLE SET search_path = pg_catalog AS $$
 SELECT target_school = NULLIF(current_setting('app.current_school_id', true), '')::bigint
 AND EXISTS (
   SELECT 1 FROM public.memberships_schoolmembership m
   JOIN public.memberships_schoolmembershiprole r ON r.membership_id = m.id
   JOIN public.accounts_user u ON u.id = m.user_id
   WHERE m.school_id = target_school
     AND m.user_id = NULLIF(current_setting('app.current_user_id', true), '')::bigint
     AND m.status = 'ACTIVE' AND r.role IN ('SCHOOL_MANAGER', 'VICE_PRINCIPAL')
     AND u.is_active AND NOT u.must_change_password)
$$;

CREATE FUNCTION public.xmansx_recovery_purge_allowed(target_school bigint, target_student bigint)
RETURNS boolean LANGUAGE plpgsql STABLE SET search_path = pg_catalog AS $$
DECLARE actor bigint; kind text; job bigint; session_actor bigint;
BEGIN
 IF target_school IS DISTINCT FROM
    NULLIF(current_setting('app.current_school_id', true), '')::bigint
    OR target_school IS DISTINCT FROM
    NULLIF(current_setting('app.recovery_purge_school', true), '')::bigint THEN
   RETURN false;
 END IF;
 actor := NULLIF(current_setting('app.recovery_purge_actor', true), '')::bigint;
 session_actor := NULLIF(current_setting('app.current_user_id', true), '')::bigint;
 kind := current_setting('app.recovery_purge_kind', true);
 IF NOT EXISTS (SELECT 1 FROM public.accounts_user u WHERE u.id = actor
                AND u.is_active AND NOT u.must_change_password) THEN RETURN false; END IF;
 IF kind = 'SCHOOL' THEN
   IF session_actor IS DISTINCT FROM actor THEN RETURN false; END IF;
   RETURN EXISTS (SELECT 1 FROM public.accounts_user u WHERE u.id = actor AND u.is_superuser)
     OR EXISTS (SELECT 1 FROM public.platform_team_platformstaffmembership p
                WHERE p.user_id = actor AND p.status = 'ACTIVE'
                  AND p.role = 'OPERATIONS_MANAGER');
 ELSIF kind = 'STUDENT' THEN
   IF target_student IS DISTINCT FROM
      NULLIF(current_setting('app.recovery_purge_student', true), '')::bigint
      OR NOT EXISTS (
        SELECT 1 FROM public.memberships_schoolmembership m
        JOIN public.memberships_schoolmembershiprole r ON r.membership_id = m.id
        WHERE m.school_id = target_school AND m.user_id = actor
          AND m.status = 'ACTIVE' AND r.role = 'SCHOOL_MANAGER') THEN RETURN false; END IF;
   job := NULLIF(current_setting('app.recovery_purge_job', true), '')::bigint;
   IF (session_actor IS NULL AND job IS NULL)
      OR (session_actor IS NOT NULL AND session_actor IS DISTINCT FROM actor)
      THEN RETURN false; END IF;
   RETURN job IS NULL OR EXISTS (
     SELECT 1 FROM public.students_studentpurgejob j
     WHERE j.id = job AND j.school_id = target_school AND j.created_by_id = actor
       AND j.status = 'RUNNING' AND j.student_ids @> jsonb_build_array(target_student));
 END IF;
 RETURN false;
END;
$$;

CREATE FUNCTION public.xmansx_recovery_source_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
BEGIN
 IF NEW.status <> 'PENDING' THEN
   RAISE EXCEPTION 'recovery source is intake only' USING ERRCODE = '23514';
 END IF;
 IF TG_OP = 'UPDATE' AND
    (to_jsonb(NEW) - ARRAY['updated_at']) IS DISTINCT FROM
    (to_jsonb(OLD) - ARRAY['updated_at']) THEN
   RAISE EXCEPTION 'recovery source binding is immutable' USING ERRCODE = '23514';
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER recovery_source_guard BEFORE INSERT OR UPDATE
ON public.parents_globalmobilechangerequest FOR EACH ROW
EXECUTE FUNCTION public.xmansx_recovery_source_guard();

CREATE FUNCTION public.xmansx_recovery_case_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
DECLARE source record; account record; actor bigint; decision record;
BEGIN
 IF TG_OP = 'DELETE' THEN
   IF NOT public.xmansx_recovery_purge_allowed(OLD.school_id, OLD.student_id) THEN
     RAISE EXCEPTION 'recovery case deletion requires scoped purge' USING ERRCODE = '23514';
   END IF;
   RETURN OLD;
 END IF;
 actor := NULLIF(current_setting('app.current_user_id', true), '')::bigint;
 IF TG_OP = 'INSERT' THEN
   SELECT * INTO source FROM public.parents_globalmobilechangerequest
   WHERE id = NEW.source_request_id;
   SELECT password, mobile, is_active INTO account FROM public.accounts_user
   WHERE id = NEW.user_id FOR SHARE;
   IF source.id IS NULL OR source.school_id <> NEW.school_id OR source.student_id <> NEW.student_id
      OR source.user_id <> NEW.user_id OR source.requested_by_id <> NEW.requested_by_id
      OR source.new_mobile_hash <> NEW.source_mobile_hash OR source.status <> 'PENDING'
      OR NOT account.is_active OR NEW.account_password_fingerprint IS DISTINCT FROM
         encode(sha256(convert_to(account.password, 'UTF8')), 'hex')
      OR NEW.account_mobile_fingerprint IS DISTINCT FROM
         encode(sha256(convert_to(account.mobile, 'UTF8')), 'hex')
      OR NEW.version <> 1 OR NEW.status <> 'PENDING'
      OR NOT EXISTS (SELECT 1 FROM public.parents_guardianstudentrelation g
                     WHERE g.school_id = NEW.school_id AND g.student_id = NEW.student_id
                       AND g.user_id = NEW.user_id) THEN
     RAISE EXCEPTION 'recovery case identity mismatch' USING ERRCODE = '23514';
   END IF;
   RETURN NEW;
 END IF;
 IF (to_jsonb(NEW) - ARRAY['status', 'version', 'updated_at']) IS DISTINCT FROM
    (to_jsonb(OLD) - ARRAY['status', 'version', 'updated_at']) THEN
   RAISE EXCEPTION 'recovery case binding is immutable' USING ERRCODE = '23514';
 END IF;
 IF NEW.version IS DISTINCT FROM OLD.version THEN
   IF pg_trigger_depth() <> 2 OR NEW.version <> OLD.version + 1
      OR NEW.status <> 'IDENTITY_REVIEW' OR OLD.status IN ('REJECTED', 'EXPIRED', 'CANCELLED') THEN
     RAISE EXCEPTION 'recovery version is database owned' USING ERRCODE = '23514';
   END IF;
   RETURN NEW;
 END IF;
 IF NEW.status = OLD.status THEN RETURN NEW; END IF;
 IF OLD.status IN ('REJECTED', 'EXPIRED', 'CANCELLED') THEN
   RAISE EXCEPTION 'recovery case is terminal' USING ERRCODE = '23514';
 END IF;
 IF NEW.status = 'EXPIRED' AND OLD.expires_at <= statement_timestamp()
    AND (public.xmansx_recovery_school_intake(OLD.school_id)
         OR public.xmansx_recovery_review_stage() IS NOT NULL) THEN RETURN NEW; END IF;
 IF NEW.status = 'CANCELLED' AND public.xmansx_recovery_school_intake(OLD.school_id)
 THEN RETURN NEW; END IF;
 IF public.xmansx_recovery_review_stage() IS NULL OR OLD.expires_at <= statement_timestamp()
    OR OLD.status = 'POLICY_BLOCKED' THEN
   RAISE EXCEPTION 'recovery review transition denied' USING ERRCODE = '23514';
 END IF;
 SELECT * INTO decision FROM public.parents_recoveryreviewdecision
 WHERE case_id = OLD.id AND case_version = OLD.version AND reviewer_id = actor
 ORDER BY id DESC LIMIT 1;
 IF decision.id IS NULL OR decision.stage <> public.xmansx_recovery_review_stage()
    OR NOT ((NEW.status = 'REJECTED' AND decision.recommendation = 'REJECT')
       OR (NEW.status = 'NEEDS_EVIDENCE' AND decision.recommendation = 'NEEDS_EVIDENCE')
       OR (NEW.status = 'AWAITING_SECOND_REVIEW' AND decision.stage = 'FIRST'
           AND decision.recommendation = 'CONTINUE_REVIEW'
           AND OLD.status IN ('PENDING', 'IDENTITY_REVIEW', 'NEEDS_EVIDENCE'))
       OR (NEW.status = 'POLICY_BLOCKED' AND decision.stage = 'SECOND'
           AND decision.recommendation = 'CONTINUE_REVIEW'
           AND OLD.status = 'AWAITING_SECOND_REVIEW')) THEN
   RAISE EXCEPTION 'recovery state requires matching independent decision' USING ERRCODE = '23514';
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER recovery_case_guard BEFORE INSERT OR UPDATE OR DELETE
ON public.parents_globalaccountrecoverycase FOR EACH ROW
EXECUTE FUNCTION public.xmansx_recovery_case_guard();

CREATE FUNCTION public.xmansx_recovery_assert_reviewable(case_uuid uuid) RETURNS void
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
DECLARE c record; account record; actor bigint;
BEGIN
 SELECT * INTO c FROM public.parents_globalaccountrecoverycase WHERE id = case_uuid FOR UPDATE;
 actor := NULLIF(current_setting('app.current_user_id', true), '')::bigint;
 SELECT password, mobile, is_active INTO account FROM public.accounts_user
 WHERE id = c.user_id FOR SHARE;
 IF c.id IS NULL OR c.school_id IS DISTINCT FROM
    NULLIF(current_setting('app.current_school_id', true), '')::bigint
    OR public.xmansx_recovery_review_stage() IS NULL
    OR c.status IN ('REJECTED', 'EXPIRED', 'CANCELLED') OR c.expires_at <= statement_timestamp()
    OR actor IN (c.user_id, c.requested_by_id)
    OR EXISTS (SELECT 1 FROM public.memberships_schoolmembership m
               WHERE m.user_id = actor AND m.school_id = c.school_id)
    OR NOT account.is_active OR c.account_password_fingerprint IS DISTINCT FROM
       encode(sha256(convert_to(account.password, 'UTF8')), 'hex')
    OR c.account_mobile_fingerprint IS DISTINCT FROM
       encode(sha256(convert_to(account.mobile, 'UTF8')), 'hex') THEN
   RAISE EXCEPTION 'recovery reviewer or account binding invalid' USING ERRCODE = '23514';
 END IF;
END;
$$;

CREATE FUNCTION public.xmansx_recovery_reference_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
DECLARE c record;
BEGIN
 IF TG_OP = 'DELETE' THEN
   SELECT * INTO c FROM public.parents_globalaccountrecoverycase WHERE id = OLD.case_id;
   IF c.id IS NULL OR NOT public.xmansx_recovery_purge_allowed(c.school_id, c.student_id) THEN
     RAISE EXCEPTION 'recovery reference deletion requires scoped purge' USING ERRCODE = '23514';
   END IF;
   RETURN OLD;
 END IF;
 PERFORM public.xmansx_recovery_assert_reviewable(NEW.case_id);
 SELECT * INTO c FROM public.parents_globalaccountrecoverycase WHERE id = NEW.case_id;
 IF NEW.school_id <> c.school_id OR NEW.expires_at > c.expires_at THEN
   RAISE EXCEPTION 'recovery reference case mismatch' USING ERRCODE = '23514';
 END IF;
 IF TG_OP = 'INSERT' THEN
   IF NEW.recorded_by_id IS DISTINCT FROM
      NULLIF(current_setting('app.current_user_id', true), '')::bigint
      OR NEW.expires_at <= statement_timestamp() OR NEW.revoked_at IS NOT NULL THEN
     RAISE EXCEPTION 'recovery reference intake invalid' USING ERRCODE = '23514';
   END IF;
 ELSIF (to_jsonb(NEW) - ARRAY['revoked_at', 'updated_at']) IS DISTINCT FROM
       (to_jsonb(OLD) - ARRAY['revoked_at', 'updated_at'])
       OR OLD.revoked_at IS NOT NULL OR NEW.revoked_at IS NULL
       OR NEW.revoked_at > statement_timestamp() THEN
   RAISE EXCEPTION 'recovery reference is immutable except one-way revocation'
   USING ERRCODE = '23514';
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER recovery_reference_guard BEFORE INSERT OR UPDATE OR DELETE
ON public.parents_recoveryevidencereference FOR EACH ROW
EXECUTE FUNCTION public.xmansx_recovery_reference_guard();

CREATE FUNCTION public.xmansx_recovery_reference_version() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
BEGIN
 UPDATE public.parents_globalaccountrecoverycase
 SET version = version + 1, status = 'IDENTITY_REVIEW', updated_at = statement_timestamp()
 WHERE id = NEW.case_id;
 RETURN NEW;
END;
$$;
CREATE TRIGGER recovery_reference_version AFTER INSERT OR UPDATE
ON public.parents_recoveryevidencereference FOR EACH ROW
EXECUTE FUNCTION public.xmansx_recovery_reference_version();

CREATE FUNCTION public.xmansx_recovery_decision_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
DECLARE c record; first_review record;
BEGIN
 IF TG_OP = 'DELETE' THEN
   SELECT * INTO c FROM public.parents_globalaccountrecoverycase WHERE id = OLD.case_id;
   IF c.id IS NULL OR NOT public.xmansx_recovery_purge_allowed(c.school_id, c.student_id) THEN
     RAISE EXCEPTION 'recovery decision deletion requires scoped purge' USING ERRCODE = '23514';
   END IF;
   RETURN OLD;
 ELSIF TG_OP = 'UPDATE' THEN
   RAISE EXCEPTION 'recovery decisions are append only' USING ERRCODE = '23514';
 END IF;
 PERFORM public.xmansx_recovery_assert_reviewable(NEW.case_id);
 SELECT * INTO c FROM public.parents_globalaccountrecoverycase WHERE id = NEW.case_id;
 IF NEW.school_id <> c.school_id OR NEW.case_version <> c.version
    OR NEW.reviewer_id IS DISTINCT FROM
       NULLIF(current_setting('app.current_user_id', true), '')::bigint
    OR NEW.stage IS DISTINCT FROM public.xmansx_recovery_review_stage()
    OR c.status = 'POLICY_BLOCKED' THEN
   RAISE EXCEPTION 'recovery decision responsibility or version invalid' USING ERRCODE = '23514';
 END IF;
 IF NEW.stage = 'SECOND' THEN
   SELECT * INTO first_review FROM public.parents_recoveryreviewdecision
   WHERE case_id = c.id AND case_version = c.version AND stage = 'FIRST';
   IF first_review.id IS NULL OR first_review.reviewer_id = NEW.reviewer_id
      OR first_review.recommendation <> 'CONTINUE_REVIEW'
      OR c.status <> 'AWAITING_SECOND_REVIEW'
      OR (NEW.recommendation = 'CONTINUE_REVIEW'
          AND first_review.evidence_fingerprint <> NEW.evidence_fingerprint) THEN
     RAISE EXCEPTION 'recovery requires distinct first and second reviewers'
     USING ERRCODE = '23514';
   END IF;
 ELSIF c.status NOT IN ('PENDING', 'IDENTITY_REVIEW', 'NEEDS_EVIDENCE') THEN
   RAISE EXCEPTION 'recovery first review state invalid' USING ERRCODE = '23514';
 END IF;
 IF NEW.recommendation = 'CONTINUE_REVIEW' THEN
   IF NEW.evidence_fingerprint !~ '^[0-9a-f]{64}$'
      OR NOT EXISTS (SELECT 1 FROM public.parents_recoveryevidencereference e
                     WHERE e.case_id = c.id AND e.kind = 'ORIGINAL_ACCOUNT_BINDING'
                       AND e.revoked_at IS NULL AND e.expires_at > statement_timestamp())
      OR (c.operation <> 'PASSWORD_RECOVERY' AND NOT EXISTS (
          SELECT 1 FROM public.parents_recoveryevidencereference e
          WHERE e.case_id = c.id AND e.kind = 'NEW_NUMBER_OWNERSHIP'
            AND e.revoked_at IS NULL AND e.expires_at > statement_timestamp())) THEN
     RAISE EXCEPTION 'recovery requires current evidence references' USING ERRCODE = '23514';
   END IF;
 ELSIF NEW.evidence_fingerprint <> '' THEN
   RAISE EXCEPTION 'recovery non-continuation evidence fingerprint invalid' USING ERRCODE = '23514';
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER recovery_decision_guard BEFORE INSERT OR UPDATE OR DELETE
ON public.parents_recoveryreviewdecision FOR EACH ROW
EXECUTE FUNCTION public.xmansx_recovery_decision_guard();

CREATE FUNCTION public.xmansx_recovery_authority_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
BEGIN
 IF (to_jsonb(NEW) - ARRAY['revoked_at', 'updated_at']) IS DISTINCT FROM
    (to_jsonb(OLD) - ARRAY['revoked_at', 'updated_at'])
    OR OLD.revoked_at IS NOT NULL OR NEW.revoked_at IS NULL THEN
   RAISE EXCEPTION 'recovery authority is immutable except one-way revocation'
   USING ERRCODE = '23514';
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER recovery_authority_guard BEFORE UPDATE
ON public.parents_recoveryreviewauthorization FOR EACH ROW
EXECUTE FUNCTION public.xmansx_recovery_authority_guard();

CREATE FUNCTION public.xmansx_recovery_same_case_school() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
DECLARE referenced_school bigint;
BEGIN
 SELECT school_id INTO referenced_school
 FROM public.parents_globalaccountrecoverycase WHERE id = NEW.case_id;
 IF referenced_school IS DISTINCT FROM NEW.school_id THEN
   RAISE EXCEPTION 'recovery case school mismatch' USING ERRCODE = '23514';
 END IF;
 RETURN NEW;
END;
$$;
"""

RECOVERY_TABLES = (
    "parents_globalaccountrecoverycase",
    "parents_recoveryevidencereference",
    "parents_recoveryreviewdecision",
    "parents_recoveryreviewauthorization",
)


def apply_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(GUARD_SQL)
    for table in RECOVERY_TABLES:
        schema_editor.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        schema_editor.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
    actor = "NULLIF(current_setting('app.current_user_id', true), '')::bigint"
    scope = "school_id = NULLIF(current_setting('app.current_school_id', true), '')::bigint"
    central = "public.xmansx_recovery_review_stage() IS NOT NULL"
    case = "parents_globalaccountrecoverycase"
    purge = "public.xmansx_recovery_purge_allowed(school_id, student_id)"
    intake = "public.xmansx_recovery_school_intake(school_id)"
    schema_editor.execute(
        f"CREATE POLICY recovery_select ON {case} FOR SELECT "
        f"USING ({central} OR {intake} OR {purge})"
    )
    schema_editor.execute(
        f"CREATE POLICY recovery_insert ON {case} FOR INSERT WITH CHECK "
        f"({intake} AND requested_by_id = {actor} AND user_id <> {actor})"
    )
    schema_editor.execute(
        f"CREATE POLICY recovery_update ON {case} FOR UPDATE "
        f"USING (({central} AND {scope}) OR {intake}) "
        f"WITH CHECK (({central} AND {scope}) OR {intake})"
    )
    schema_editor.execute(f"CREATE POLICY recovery_delete ON {case} FOR DELETE USING ({purge})")
    for table in ("parents_recoveryevidencereference", "parents_recoveryreviewdecision"):
        purgable = (
            "EXISTS (SELECT 1 FROM public.parents_globalaccountrecoverycase c "
            f"WHERE c.id = {table}.case_id "
            "AND public.xmansx_recovery_purge_allowed(c.school_id, c.student_id))"
        )
        schema_editor.execute(
            f"CREATE POLICY recovery_select ON {table} FOR SELECT USING ({central} OR {purgable})"
        )
        schema_editor.execute(
            f"CREATE POLICY recovery_insert ON {table} FOR INSERT "
            f"WITH CHECK ({central} AND {scope})"
        )
        schema_editor.execute(
            f"CREATE POLICY recovery_update ON {table} FOR UPDATE "
            f"USING ({central} AND {scope}) WITH CHECK ({central} AND {scope})"
        )
        schema_editor.execute(
            f"CREATE POLICY recovery_delete ON {table} FOR DELETE USING ({purgable})"
        )
    grant = "parents_recoveryreviewauthorization"
    schema_editor.execute(
        f"CREATE POLICY recovery_select ON {grant} FOR SELECT USING (reviewer_id = {actor})"
    )
    for operation in ("INSERT", "UPDATE", "DELETE"):
        clause = "WITH CHECK (false)" if operation == "INSERT" else "USING (false)"
        schema_editor.execute(
            f"CREATE POLICY recovery_{operation.lower()} ON {grant} FOR {operation} {clause}"
        )
    schema_editor.execute(
        "CREATE POLICY recovery_central_source_select ON parents_globalmobilechangerequest "
        f"FOR SELECT USING ({central})"
    )
    for table, target, column in (
        (
            "parents_globalaccountrecoverycase",
            "parents_globalmobilechangerequest",
            "source_request_id",
        ),
        ("parents_globalaccountrecoverycase", "students_student", "student_id"),
        ("parents_recoveryevidencereference", "parents_globalaccountrecoverycase", "case_id"),
        ("parents_recoveryreviewdecision", "parents_globalaccountrecoverycase", "case_id"),
    ):
        trigger = f"same_school_{table}_{column}"[:63]
        function = (
            "public.xmansx_recovery_same_case_school()"
            if column == "case_id"
            else f"public.xmansx_enforce_same_school_fk('public', '{target}', '{column}')"
        )
        schema_editor.execute(
            f"CREATE CONSTRAINT TRIGGER {trigger} AFTER INSERT OR UPDATE ON {table} "
            "DEFERRABLE INITIALLY IMMEDIATE FOR EACH ROW "
            f"EXECUTE FUNCTION {function}"
        )


def remove_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "DROP POLICY IF EXISTS recovery_central_source_select ON parents_globalmobilechangerequest"
    )
    for table in RECOVERY_TABLES:
        for column in ("source_request_id", "student_id", "case_id"):
            trigger = f"same_school_{table}_{column}"[:63]
            schema_editor.execute(f"DROP TRIGGER IF EXISTS {trigger} ON {table}")
        for operation in ("select", "insert", "update", "delete"):
            schema_editor.execute(f"DROP POLICY IF EXISTS recovery_{operation} ON {table}")
        schema_editor.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        schema_editor.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
    for table, names in (
        ("parents_globalmobilechangerequest", ("source_guard",)),
        ("parents_globalaccountrecoverycase", ("case_guard",)),
        ("parents_recoveryevidencereference", ("reference_guard", "reference_version")),
        ("parents_recoveryreviewdecision", ("decision_guard",)),
        ("parents_recoveryreviewauthorization", ("authority_guard",)),
    ):
        for name in names:
            schema_editor.execute(f"DROP TRIGGER IF EXISTS recovery_{name} ON {table}")
    for function in (
        "source_guard()",
        "case_guard()",
        "reference_guard()",
        "reference_version()",
        "decision_guard()",
        "authority_guard()",
        "same_case_school()",
        "assert_reviewable(uuid)",
        "school_intake(bigint)",
        "purge_allowed(bigint, bigint)",
        "review_stage()",
    ):
        schema_editor.execute(f"DROP FUNCTION IF EXISTS public.xmansx_recovery_{function}")


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_must_change_password"),
        ("parents", "0005_immutable_relation_identity"),
        ("platform_team", "0001_initial"),
        ("schools", "0006_schoolsettings_absence_sms_message_template"),
        ("students", "0008_guardian_contact_revision_db_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalAccountRecoveryCase",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("MOBILE_CHANGE", "تغيير رقم الدخول"),
                            ("PASSWORD_RECOVERY", "استعادة كلمة المرور"),
                            ("MOBILE_AND_PASSWORD", "استعادة الرقم وكلمة المرور"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "بانتظار المراجعة"),
                            ("IDENTITY_REVIEW", "مراجعة هوية الحساب الأصلي"),
                            ("NEEDS_EVIDENCE", "تحتاج أدلة مستقلة"),
                            ("AWAITING_SECOND_REVIEW", "بانتظار مراجع مستقل ثان"),
                            ("POLICY_BLOCKED", "الإتمام محجوب لغياب سياسة معتمدة"),
                            ("REJECTED", "مرفوضة"),
                            ("EXPIRED", "منتهية"),
                            ("CANCELLED", "ملغاة"),
                        ],
                        default="PENDING",
                        max_length=24,
                    ),
                ),
                ("source_mobile_hash", models.CharField(max_length=64)),
                ("account_password_fingerprint", models.CharField(max_length=64)),
                ("account_mobile_fingerprint", models.CharField(max_length=64)),
                ("version", models.PositiveIntegerField(db_default=1, default=1, editable=False)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="RecoveryEvidenceReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ORIGINAL_ACCOUNT_BINDING", "مرجع مستقل لصاحب الحساب الأصلي"),
                            ("NEW_NUMBER_OWNERSHIP", "مرجع ملكية الرقم المطلوب"),
                        ],
                        max_length=30,
                    ),
                ),
                ("reference_id", models.UUIDField()),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecoveryReviewAuthorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("authorization_reference", models.UUIDField()),
                (
                    "stage",
                    models.CharField(
                        choices=[("FIRST", "مراجعة أولى"), ("SECOND", "مراجعة مستقلة ثانية")],
                        max_length=6,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecoveryReviewDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[("FIRST", "مراجعة أولى"), ("SECOND", "مراجعة مستقلة ثانية")],
                        max_length=6,
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("CONTINUE_REVIEW", "استكمال مراجعة لا يجيز الاستعادة"),
                            ("NEEDS_EVIDENCE", "طلب أدلة مستقلة"),
                            ("REJECT", "رفض"),
                        ],
                        max_length=20,
                    ),
                ),
                ("case_version", models.PositiveIntegerField()),
                ("evidence_fingerprint", models.CharField(max_length=64)),
                ("note_encrypted", models.TextField(blank=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="globalmobilechangerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("status", "PENDING")), name="parent_global_change_intake_only"
            ),
        ),
        migrations.AddField(
            model_name="globalaccountrecoverycase",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="globalaccountrecoverycase",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="schools.school"
            ),
        ),
        migrations.AddField(
            model_name="globalaccountrecoverycase",
            name="source_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recovery_case",
                to="parents.globalmobilechangerequest",
            ),
        ),
        migrations.AddField(
            model_name="globalaccountrecoverycase",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="students.student"
            ),
        ),
        migrations.AddField(
            model_name="globalaccountrecoverycase",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recoveryevidencereference",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="parents.globalaccountrecoverycase"
            ),
        ),
        migrations.AddField(
            model_name="recoveryevidencereference",
            name="recorded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="recoveryevidencereference",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="schools.school"
            ),
        ),
        migrations.AddField(
            model_name="recoveryreviewauthorization",
            name="granted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recoveryreviewauthorization",
            name="reviewer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="recoveryreviewdecision",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="parents.globalaccountrecoverycase"
            ),
        ),
        migrations.AddField(
            model_name="recoveryreviewdecision",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="recoveryreviewdecision",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="schools.school"
            ),
        ),
        migrations.AddIndex(
            model_name="globalaccountrecoverycase",
            index=models.Index(
                fields=["school", "status", "created_at"], name="recovery_school_queue_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="globalaccountrecoverycase",
            index=models.Index(fields=["status", "expires_at"], name="recovery_expiry_idx"),
        ),
        migrations.AddConstraint(
            model_name="globalaccountrecoverycase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "PENDING",
                            "IDENTITY_REVIEW",
                            "NEEDS_EVIDENCE",
                            "AWAITING_SECOND_REVIEW",
                            "POLICY_BLOCKED",
                            "REJECTED",
                            "EXPIRED",
                            "CANCELLED",
                        ],
                    )
                ),
                name="recovery_review_only_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="recoveryreviewauthorization",
            constraint=models.CheckConstraint(
                condition=models.Q(("stage__in", ["FIRST", "SECOND"])),
                name="recovery_authority_stage_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="globalaccountrecoverycase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("operation__in", ["MOBILE_CHANGE", "PASSWORD_RECOVERY", "MOBILE_AND_PASSWORD"])
                ),
                name="recovery_operation_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recoveryevidencereference",
            constraint=models.UniqueConstraint(
                fields=("case", "kind", "reference_id"), name="recovery_ref_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="recoveryevidencereference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind__in", ["ORIGINAL_ACCOUNT_BINDING", "NEW_NUMBER_OWNERSHIP"])
                ),
                name="recovery_ref_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recoveryreviewauthorization",
            constraint=models.CheckConstraint(
                condition=models.Q(("reviewer", models.F("granted_by")), _negated=True),
                name="recovery_no_self_authorization",
            ),
        ),
        migrations.AddConstraint(
            model_name="recoveryreviewdecision",
            constraint=models.UniqueConstraint(
                fields=("case", "case_version", "stage"), name="recovery_stage_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="recoveryreviewdecision",
            constraint=models.UniqueConstraint(
                fields=("case", "case_version", "reviewer"), name="recovery_reviewer_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="recoveryreviewdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("stage__in", ["FIRST", "SECOND"])), name="recovery_stage_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="recoveryreviewdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("recommendation__in", ["CONTINUE_REVIEW", "NEEDS_EVIDENCE", "REJECT"])
                ),
                name="recovery_recommendation_valid",
            ),
        ),
        migrations.RunPython(apply_guards, remove_guards),
    ]
