# Generated by Django 5.2.17 on 2026-10-08 08:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


GUARD_SQL = r"""
CREATE FUNCTION public.xmansx_parent_email_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
DECLARE actor bigint; action text; proof record;
BEGIN
 IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = current_user AND rolsuper)
 THEN RETURN NEW; END IF;
 actor := NULLIF(current_setting('app.current_user_id', true),'')::bigint;
 action := current_setting('app.parent_email_action', true);
 IF NEW.user_id IS DISTINCT FROM actor
    OR NULLIF(current_setting('app.current_school_id', true),'') IS NOT NULL THEN
   RAISE EXCEPTION 'recovery email requires its global account owner' USING ERRCODE='23514';
 END IF;
 IF TG_OP = 'INSERT' THEN
   IF action <> 'ENROLL' OR NEW.verified_at IS NOT NULL OR NEW.current_email_hash IS NOT NULL
      OR NEW.current_email_encrypted <> '' OR NEW.revision <> 1 THEN
     RAISE EXCEPTION 'initial recovery email cannot be verified' USING ERRCODE='23514';
   END IF;
   RETURN NEW;
 END IF;
 IF NEW.id <> OLD.id OR NEW.user_id <> OLD.user_id THEN
   RAISE EXCEPTION 'recovery email account binding is immutable' USING ERRCODE='23514';
 END IF;
 IF action = 'ENROLL' THEN
   IF NEW.current_email_encrypted IS DISTINCT FROM OLD.current_email_encrypted
      OR NEW.current_email_hash IS DISTINCT FROM OLD.current_email_hash
      OR NEW.verified_at IS DISTINCT FROM OLD.verified_at OR NEW.revision <> OLD.revision
      OR NEW.pending_revision <> OLD.pending_revision + 1 THEN
     RAISE EXCEPTION 'email enrollment cannot replace verified ownership' USING ERRCODE='23514';
   END IF;
   RETURN NEW;
 END IF;
 IF action = 'VERIFY' THEN
   SELECT d.* INTO proof FROM public.parents_accountrecoveryemaildelivery d
   JOIN public.accounts_user u ON u.id=d.user_id
   WHERE d.recovery_email_id=OLD.id AND d.user_id=actor
     AND d.purpose='RECOVERY_EMAIL_VERIFICATION'
     AND d.token_hash=NULLIF(current_setting('app.parent_email_token',true),'')
     AND d.consumed_at IS NULL AND d.revoked_at IS NULL
     AND d.expires_at>statement_timestamp()
     AND d.status IN ('SENDING','SUBMITTED_TO_PROVIDER','UNKNOWN')
     AND d.password_fingerprint=encode(sha256(convert_to(u.password,'UTF8')),'hex')
     AND d.mobile_fingerprint=encode(sha256(convert_to(u.mobile,'UTF8')),'hex');
   IF proof.id IS NULL OR proof.email_hash<>OLD.pending_email_hash
      OR proof.email_revision<>OLD.pending_revision
      OR NEW.current_email_hash IS DISTINCT FROM OLD.pending_email_hash
      OR NEW.current_email_encrypted IS DISTINCT FROM OLD.pending_email_encrypted
      OR NEW.verified_at IS NULL OR NEW.revision<>OLD.revision+1
      OR NEW.pending_revision<>OLD.pending_revision
      OR NEW.pending_email_hash<>'' OR NEW.pending_email_encrypted<>'' THEN
     RAISE EXCEPTION 'email verification requires a current bearer proof' USING ERRCODE='23514';
   END IF;
   RETURN NEW;
 END IF;
 RAISE EXCEPTION 'recovery email change denied' USING ERRCODE='23514';
END;
$$;
CREATE TRIGGER parent_email_guard BEFORE INSERT OR UPDATE
ON public.parents_accountrecoveryemail FOR EACH ROW
EXECUTE FUNCTION public.xmansx_parent_email_guard();

CREATE FUNCTION public.xmansx_parent_email_delivery_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
DECLARE action text; actor bigint; account record; email record;
BEGIN
 IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = current_user AND rolsuper)
 THEN RETURN NEW; END IF;
 action := current_setting('app.parent_email_action',true);
 actor := NULLIF(current_setting('app.current_user_id',true),'')::bigint;
 IF NEW.user_id IS DISTINCT FROM actor OR
    NULLIF(current_setting('app.current_school_id',true),'') IS NOT NULL THEN
   RAISE EXCEPTION 'recovery delivery requires exact global account' USING ERRCODE='23514';
 END IF;
 IF TG_OP='INSERT' THEN
   SELECT * INTO email FROM public.parents_accountrecoveryemail WHERE id=NEW.recovery_email_id;
   SELECT * INTO account FROM public.accounts_user WHERE id=NEW.user_id FOR SHARE;
   IF email.id IS NULL OR email.user_id<>NEW.user_id OR NOT account.is_active
      OR account.must_change_password OR NEW.status<>'PENDING' OR NEW.token_hash IS NOT NULL
      OR NEW.expires_at IS NOT NULL OR NEW.consumed_at IS NOT NULL
      OR NEW.revoked_at IS NOT NULL OR NEW.attempt_started_at IS NOT NULL
      OR NEW.password_fingerprint<>encode(sha256(convert_to(account.password,'UTF8')),'hex')
      OR NEW.mobile_fingerprint<>encode(sha256(convert_to(account.mobile,'UTF8')),'hex')
      OR NOT ((action='ENROLL' AND NEW.purpose='RECOVERY_EMAIL_VERIFICATION'
          AND NEW.email_hash=email.pending_email_hash AND NEW.email_revision=email.pending_revision)
        OR (action='REQUEST' AND NEW.purpose='PASSWORD_RESET' AND email.verified_at IS NOT NULL
          AND NEW.email_hash=email.current_email_hash AND NEW.email_revision=email.revision)) THEN
     RAISE EXCEPTION 'recovery delivery binding mismatch' USING ERRCODE='23514';
   END IF;
   RETURN NEW;
 END IF;
 IF (to_jsonb(NEW)-ARRAY['status','token_hash','expires_at','attempt_started_at',
             'consumed_at','revoked_at','provider_reference','error_code','updated_at'])
    IS DISTINCT FROM (to_jsonb(OLD)-ARRAY['status','token_hash','expires_at','attempt_started_at',
             'consumed_at','revoked_at','provider_reference','error_code','updated_at']) THEN
   RAISE EXCEPTION 'recovery delivery identity is immutable' USING ERRCODE='23514';
 END IF;
 IF OLD.consumed_at IS NOT NULL AND NEW.consumed_at IS DISTINCT FROM OLD.consumed_at
    OR OLD.revoked_at IS NOT NULL AND NEW.revoked_at IS DISTINCT FROM OLD.revoked_at THEN
   RAISE EXCEPTION 'recovery bearer cannot be restored' USING ERRCODE='23514';
 END IF;
 IF NEW.token_hash IS DISTINCT FROM OLD.token_hash
    OR NEW.expires_at IS DISTINCT FROM OLD.expires_at
    OR NEW.attempt_started_at IS DISTINCT FROM OLD.attempt_started_at THEN
   IF action<>'DELIVER' OR NEW.id::text<>current_setting('app.parent_email_delivery',true)
      OR OLD.status<>'PENDING' OR NEW.status<>'SENDING' OR OLD.token_hash IS NOT NULL
      OR NEW.token_hash IS NULL OR NEW.attempt_started_at IS NULL OR NEW.expires_at IS NULL THEN
     RAISE EXCEPTION 'recovery bearer is issued once by its worker' USING ERRCODE='23514';
   END IF;
 END IF;
 IF NEW.status IS DISTINCT FROM OLD.status THEN
   IF action<>'DELIVER' OR NEW.id::text<>current_setting('app.parent_email_delivery',true)
      OR OLD.status NOT IN ('PENDING','SENDING')
      OR NEW.status NOT IN ('SENDING','SUBMITTED_TO_PROVIDER','FAILED','UNKNOWN','CANCELLED') THEN
     RAISE EXCEPTION 'recovery delivery transition denied' USING ERRCODE='23514';
   END IF;
 END IF;
 IF NEW.consumed_at IS DISTINCT FROM OLD.consumed_at THEN
   IF action NOT IN ('VERIFY','RESET') OR OLD.token_hash IS DISTINCT FROM
      NULLIF(current_setting('app.parent_email_token',true),'')
      OR OLD.expires_at<=statement_timestamp() OR OLD.revoked_at IS NOT NULL
      OR NEW.consumed_at IS NULL OR
      (action='VERIFY' AND OLD.purpose<>'RECOVERY_EMAIL_VERIFICATION') OR
      (action='RESET' AND OLD.purpose<>'PASSWORD_RESET') THEN
     RAISE EXCEPTION 'recovery bearer consumption denied' USING ERRCODE='23514';
   END IF;
 END IF;
 IF action NOT IN ('ENROLL','REQUEST','VERIFY','RESET','DELIVER') THEN
   RAISE EXCEPTION 'recovery delivery change denied' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER parent_email_delivery_guard BEFORE INSERT OR UPDATE
ON public.parents_accountrecoveryemaildelivery FOR EACH ROW
EXECUTE FUNCTION public.xmansx_parent_email_delivery_guard();

CREATE FUNCTION public.xmansx_parent_registration_email_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
BEGIN
 IF NEW.email_encrypted IS DISTINCT FROM OLD.email_encrypted
    OR NEW.email_hash IS DISTINCT FROM OLD.email_hash
    OR NEW.email_masked IS DISTINCT FROM OLD.email_masked THEN
   RAISE EXCEPTION 'registration recovery email is immutable' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER parent_registration_email_guard BEFORE UPDATE
ON public.parents_guardianregistrationrequest FOR EACH ROW
EXECUTE FUNCTION public.xmansx_parent_registration_email_guard();
"""


def apply_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(GUARD_SQL)
    actor = "NULLIF(current_setting('app.current_user_id',true),'')::bigint"
    global_scope = "NULLIF(current_setting('app.current_school_id',true),'') IS NULL"
    exact = "id::text=NULLIF(current_setting('app.parent_email_delivery',true),'')"
    bearer = "token_hash=NULLIF(current_setting('app.parent_email_token',true),'')"
    delivery = "parents_accountrecoveryemaildelivery"
    email = "parents_accountrecoveryemail"
    for table in (email, delivery):
        schema_editor.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        schema_editor.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
    schema_editor.execute(
        f"CREATE POLICY recovery_email_delivery_select ON {delivery} FOR SELECT "
        f"USING ({global_scope} AND (user_id={actor} OR {exact} OR {bearer}))"
    )
    schema_editor.execute(
        f"CREATE POLICY recovery_email_delivery_insert ON {delivery} FOR INSERT "
        f"WITH CHECK ({global_scope} AND user_id={actor} "
        "AND current_setting('app.parent_email_action',true) IN ('ENROLL','REQUEST'))"
    )
    schema_editor.execute(
        f"CREATE POLICY recovery_email_delivery_update ON {delivery} FOR UPDATE "
        f"USING ({global_scope} AND user_id={actor}) "
        f"WITH CHECK ({global_scope} AND user_id={actor})"
    )
    schema_editor.execute(
        f"CREATE POLICY recovery_email_select ON {email} FOR SELECT USING ({global_scope} AND "
        f"(user_id={actor} OR EXISTS (SELECT 1 FROM public.{delivery} d "
        f"WHERE d.recovery_email_id={email}.id AND "
        "(d.id::text=NULLIF(current_setting('app.parent_email_delivery',true),'') "
        "OR d.token_hash=NULLIF(current_setting('app.parent_email_token',true),'')))))"
    )
    schema_editor.execute(
        f"CREATE POLICY recovery_email_insert ON {email} FOR INSERT "
        f"WITH CHECK ({global_scope} AND user_id={actor} "
        "AND current_setting('app.parent_email_action',true)='ENROLL')"
    )
    schema_editor.execute(
        f"CREATE POLICY recovery_email_update ON {email} FOR UPDATE "
        f"USING ({global_scope} AND user_id={actor}) "
        f"WITH CHECK ({global_scope} AND user_id={actor})"
    )


def remove_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for table, trigger in (
        ("parents_guardianregistrationrequest", "parent_registration_email_guard"),
        ("parents_accountrecoveryemaildelivery", "parent_email_delivery_guard"),
        ("parents_accountrecoveryemail", "parent_email_guard"),
    ):
        schema_editor.execute(f"DROP TRIGGER {trigger} ON {table}")
    for function in ("xmansx_parent_registration_email_guard", "xmansx_parent_email_delivery_guard",
                     "xmansx_parent_email_guard"):
        schema_editor.execute(f"DROP FUNCTION public.{function}()")


class Migration(migrations.Migration):

    dependencies = [
        ("parents", "0006_review_only_account_recovery"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="guardianregistrationrequest",
            name="email_encrypted",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AddField(
            model_name="guardianregistrationrequest",
            name="email_hash",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="guardianregistrationrequest",
            name="email_masked",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=254
            ),
        ),
        migrations.CreateModel(
            name="AccountRecoveryEmail",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current_email_encrypted", models.TextField(blank=True, default="")),
                (
                    "current_email_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("pending_email_encrypted", models.TextField(blank=True, default="")),
                (
                    "pending_email_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("pending_revision", models.PositiveIntegerField(default=1)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountRecoveryEmailDelivery",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("RECOVERY_EMAIL_VERIFICATION", "توثيق بريد الاسترداد"),
                            ("PASSWORD_RESET", "استعادة كلمة المرور"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "قيد الانتظار"),
                            ("SENDING", "قيد الإرسال"),
                            ("SUBMITTED_TO_PROVIDER", "قبله مزود البريد"),
                            ("FAILED", "فشل الإرسال"),
                            ("UNKNOWN", "نتيجة غير مؤكدة"),
                            ("CANCELLED", "ملغاة"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("email_hash", models.CharField(max_length=64)),
                ("email_revision", models.PositiveIntegerField()),
                ("password_fingerprint", models.CharField(max_length=64)),
                ("mobile_fingerprint", models.CharField(max_length=64)),
                (
                    "token_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_started_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_reference",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=60)),
                (
                    "recovery_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parents.accountrecoveryemail",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="accountrecoveryemail",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("current_email_encrypted", ""),
                        ("current_email_hash__isnull", True),
                        ("verified_at__isnull", True),
                    ),
                    models.Q(
                        ("current_email_hash__isnull", False),
                        ("verified_at__isnull", False),
                        models.Q(("current_email_encrypted", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="recovery_email_verified_binding",
            ),
        ),
        migrations.AddIndex(
            model_name="accountrecoveryemaildelivery",
            index=models.Index(
                fields=["user", "purpose", "-created_at"],
                name="recovery_email_outbox_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountrecoveryemaildelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("purpose__in", ["RECOVERY_EMAIL_VERIFICATION", "PASSWORD_RESET"])
                ),
                name="recovery_email_purpose_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountrecoveryemaildelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "PENDING",
                            "SENDING",
                            "SUBMITTED_TO_PROVIDER",
                            "FAILED",
                            "UNKNOWN",
                            "CANCELLED",
                        ],
                    )
                ),
                name="recovery_email_delivery_valid",
            ),
        ),
        migrations.RunPython(apply_guards, remove_guards),
    ]
