# ruff: noqa: S608, E501
# Generated by Django 5.2.18 on 2026-10-09 01:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

GUARDS = r"""
CREATE FUNCTION public.xmansx_parent_family_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog AS $$
BEGIN
 IF TG_OP='INSERT' THEN
   IF NEW.consumed_at IS NOT NULL OR NEW.activated_user_id IS NOT NULL
      OR NEW.revoked_at IS NOT NULL OR NEW.delivery_status<>'PENDING'
      OR NEW.approved_by_id IS NULL OR length(btrim(NEW.verification_note))<10 THEN
     RAISE EXCEPTION 'family invitation requires a fresh school approval' USING ERRCODE='23514';
   END IF;
   RETURN NEW;
 END IF;
 IF TG_OP='DELETE' THEN
   UPDATE public.parents_guardianactivation a
   SET revoked_at=statement_timestamp(), updated_at=statement_timestamp()
   WHERE a.used_at IS NULL AND a.revoked_at IS NULL AND EXISTS (
     SELECT 1 FROM public.parents_guardianfamilyinvitationchild c
     WHERE c.invitation_id=OLD.id AND c.activation_id=a.id);
   RETURN OLD;
 END IF;
 IF NEW.school_id<>OLD.school_id OR NEW.token_hash<>OLD.token_hash
    OR NEW.mobile_hash<>OLD.mobile_hash OR NEW.mobile_encrypted<>OLD.mobile_encrypted
    OR NEW.mobile_masked<>OLD.mobile_masked OR NEW.name<>OLD.name
    OR NEW.expires_at IS DISTINCT FROM OLD.expires_at
    OR NEW.verification_note<>OLD.verification_note
    OR (NEW.approved_by_id IS DISTINCT FROM OLD.approved_by_id AND NEW.approved_by_id IS NOT NULL) THEN
   RAISE EXCEPTION 'family invitation proof is immutable' USING ERRCODE='23514';
 END IF;
 IF OLD.consumed_at IS NOT NULL AND (
    NEW.consumed_at IS DISTINCT FROM OLD.consumed_at
    OR (NEW.activated_user_id IS DISTINCT FROM OLD.activated_user_id AND NEW.activated_user_id IS NOT NULL))
    OR OLD.revoked_at IS NOT NULL AND NEW.revoked_at IS DISTINCT FROM OLD.revoked_at THEN
   RAISE EXCEPTION 'family invitation cannot be replayed' USING ERRCODE='23514';
 END IF;
 IF NEW.consumed_at IS DISTINCT FROM OLD.consumed_at THEN
   IF NEW.consumed_at IS NULL OR NEW.activated_user_id IS NULL
      OR OLD.revoked_at IS NOT NULL OR OLD.expires_at<=statement_timestamp()
      OR OLD.delivery_status NOT IN ('SENDING','SENT','UNKNOWN')
      OR current_setting('app.parent_family_invitation_hash',true) IS DISTINCT FROM OLD.token_hash
      OR NOT EXISTS (SELECT 1 FROM public.parents_guardianfamilyinvitationchild WHERE invitation_id=OLD.id)
      OR EXISTS (
        SELECT 1 FROM public.parents_guardianfamilyinvitationchild c
        JOIN public.parents_guardianactivation a ON a.id=c.activation_id
        JOIN public.students_student s ON s.id=c.student_id
        WHERE c.invitation_id=OLD.id AND (
          a.used_at IS NULL OR a.activated_user_id IS DISTINCT FROM NEW.activated_user_id
          OR a.revoked_at IS NOT NULL OR a.contact_revision<>s.guardian_contact_revision
          OR s.status<>'ACTIVE' OR s.merged_into_id IS NOT NULL
          OR NOT EXISTS (SELECT 1 FROM public.parents_guardianstudentrelation r
            WHERE r.school_id=OLD.school_id AND r.student_id=c.student_id
              AND r.user_id=NEW.activated_user_id AND r.status='ACTIVE'))) THEN
     RAISE EXCEPTION 'family consumption requires its exact bearer and every child proof' USING ERRCODE='23514';
   END IF;
 ELSIF NEW.activated_user_id IS DISTINCT FROM OLD.activated_user_id AND NEW.activated_user_id IS NOT NULL THEN
   RAISE EXCEPTION 'family account binding requires consumption' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER parent_family_guard BEFORE INSERT OR UPDATE OR DELETE
ON public.parents_guardianfamilyinvitation FOR EACH ROW
EXECUTE FUNCTION public.xmansx_parent_family_guard();

CREATE FUNCTION public.xmansx_parent_family_child_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog AS $$
BEGIN
 IF TG_OP='DELETE' THEN
   UPDATE public.parents_guardianfamilyinvitation SET revoked_at=statement_timestamp(),
     updated_at=statement_timestamp()
   WHERE id=OLD.invitation_id AND consumed_at IS NULL AND revoked_at IS NULL;
   UPDATE public.parents_guardianactivation SET revoked_at=statement_timestamp(),
     updated_at=statement_timestamp()
   WHERE id=OLD.activation_id AND used_at IS NULL AND revoked_at IS NULL;
   RETURN OLD;
 END IF;
 IF TG_OP='UPDATE' AND (NEW.school_id<>OLD.school_id OR NEW.student_id<>OLD.student_id
    OR NEW.activation_id<>OLD.activation_id OR NEW.invitation_id<>OLD.invitation_id) THEN
   RAISE EXCEPTION 'family child binding is immutable' USING ERRCODE='23514';
 END IF;
 IF NOT EXISTS (
   SELECT 1 FROM public.parents_guardianfamilyinvitation f
   JOIN public.parents_guardianactivation a ON a.id=NEW.activation_id
   JOIN public.parents_guardianregistrationrequest r ON r.id=a.request_id
   WHERE f.id=NEW.invitation_id AND f.school_id=NEW.school_id AND a.school_id=NEW.school_id
     AND a.student_id=NEW.student_id AND r.student_id=NEW.student_id
     AND r.school_id=NEW.school_id AND r.mobile_hash=f.mobile_hash
     AND r.approved_by_id=f.approved_by_id AND r.status='APPROVED'
     AND r.contact_bound AND a.delivery_channel='SMS'
     AND a.used_at IS NULL AND a.revoked_at IS NULL
     AND f.consumed_at IS NULL AND f.revoked_at IS NULL) THEN
   RAISE EXCEPTION 'family child requires its exact same-school approval' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER parent_family_child_guard BEFORE INSERT OR UPDATE OR DELETE
ON public.parents_guardianfamilyinvitationchild FOR EACH ROW
EXECUTE FUNCTION public.xmansx_parent_family_child_guard();

CREATE FUNCTION public.xmansx_parent_family_activation_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog AS $$
BEGIN
 IF NEW.used_at IS DISTINCT FROM OLD.used_at
    AND EXISTS (SELECT 1 FROM public.parents_guardianfamilyinvitationchild WHERE activation_id=OLD.id)
    AND NOT EXISTS (
      SELECT 1 FROM public.parents_guardianfamilyinvitationchild c
      JOIN public.parents_guardianfamilyinvitation f ON f.id=c.invitation_id
      WHERE c.activation_id=OLD.id AND f.revoked_at IS NULL AND f.consumed_at IS NULL
        AND f.expires_at>statement_timestamp()
        AND f.token_hash=NULLIF(current_setting('app.parent_family_invitation_hash',true),'')
        AND f.delivery_status IN ('SENDING','SENT','UNKNOWN')) THEN
   RAISE EXCEPTION 'family activation requires the live family bearer' USING ERRCODE='23514';
 END IF;
 IF EXISTS (SELECT 1 FROM public.parents_guardianfamilyinvitationchild WHERE activation_id=OLD.id)
    AND (NEW.token_hash IS DISTINCT FROM OLD.token_hash OR NEW.expires_at IS DISTINCT FROM OLD.expires_at
      OR OLD.used_at IS NOT NULL AND (NEW.used_at IS DISTINCT FROM OLD.used_at
        OR (NEW.activated_user_id IS DISTINCT FROM OLD.activated_user_id AND NEW.activated_user_id IS NOT NULL))
      OR OLD.revoked_at IS NOT NULL AND NEW.revoked_at IS DISTINCT FROM OLD.revoked_at) THEN
   RAISE EXCEPTION 'family activation proof cannot be replaced or replayed' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER parent_family_activation_guard BEFORE UPDATE ON public.parents_guardianactivation
FOR EACH ROW EXECUTE FUNCTION public.xmansx_parent_family_activation_guard();
"""


def forward(apps, schema_editor):
    school = "NULLIF(current_setting('app.current_school_id',true),'')::bigint"
    scope = f"(current_setting('app.rls_bypass',true)='on' OR school_id={school})"
    for table in ("parents_guardianfamilyinvitation", "parents_guardianfamilyinvitationchild"):
        select = scope
        if table == "parents_guardianfamilyinvitation":
            select += " OR token_hash=NULLIF(current_setting('app.parent_family_invitation_hash',true),'')"
        schema_editor.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        schema_editor.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        schema_editor.execute(f"CREATE POLICY family_select ON {table} FOR SELECT USING ({select})")
        schema_editor.execute(
            f"CREATE POLICY family_insert ON {table} FOR INSERT WITH CHECK ({scope})"
        )
        schema_editor.execute(
            f"CREATE POLICY family_update ON {table} FOR UPDATE USING ({scope}) WITH CHECK ({scope})"
        )
        schema_editor.execute(f"CREATE POLICY family_delete ON {table} FOR DELETE USING ({scope})")
    for column, target in (
        ("student_id", "students_student"),
        ("activation_id", "parents_guardianactivation"),
    ):
        schema_editor.execute(
            f"CREATE CONSTRAINT TRIGGER family_same_school_{column} AFTER INSERT OR UPDATE "
            "ON parents_guardianfamilyinvitationchild DEFERRABLE INITIALLY IMMEDIATE FOR EACH ROW "
            f"EXECUTE FUNCTION public.xmansx_enforce_same_school_fk('public','{target}','{column}')"
        )
    schema_editor.execute(GUARDS)


def backward(apps, schema_editor):
    schema_editor.execute(r"""
LOCK TABLE public.parents_guardianfamilyinvitation, public.parents_guardianfamilyinvitationchild
IN ACCESS EXCLUSIVE MODE;
DO $$ BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname=current_user AND (rolsuper OR rolbypassrls))
    OR EXISTS (SELECT 1 FROM public.parents_guardianfamilyinvitation)
    OR EXISTS (SELECT 1 FROM public.parents_guardianfamilyinvitationchild) THEN
   RAISE EXCEPTION 'family rollback requires empty synthetic tables and a trusted migration role'
     USING ERRCODE='23514';
 END IF;
END $$;
DROP TRIGGER parent_family_activation_guard ON public.parents_guardianactivation;
DROP FUNCTION public.xmansx_parent_family_activation_guard();
DROP TRIGGER parent_family_child_guard ON public.parents_guardianfamilyinvitationchild;
DROP FUNCTION public.xmansx_parent_family_child_guard();
DROP TRIGGER parent_family_guard ON public.parents_guardianfamilyinvitation;
DROP FUNCTION public.xmansx_parent_family_guard();
""")
    for table in ("parents_guardianfamilyinvitation", "parents_guardianfamilyinvitationchild"):
        for policy in ("family_select", "family_insert", "family_update", "family_delete"):
            schema_editor.execute(f"DROP POLICY {policy} ON {table}")
        schema_editor.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        schema_editor.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
    for column in ("student_id", "activation_id"):
        schema_editor.execute(
            f"DROP TRIGGER family_same_school_{column} ON parents_guardianfamilyinvitationchild"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("parents", "0009_email_activation"),
        ("schools", "0006_schoolsettings_absence_sms_message_template"),
        ("students", "0008_guardian_contact_revision_db_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuardianFamilyInvitation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("mobile_encrypted", models.TextField()),
                ("mobile_hash", models.CharField(max_length=64)),
                ("mobile_masked", models.CharField(max_length=20)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("verification_note", models.CharField(max_length=600)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_status", models.CharField(default="PENDING", max_length=12)),
                ("provider_reference", models.CharField(blank=True, max_length=100)),
                ("failure_code", models.CharField(blank=True, max_length=60)),
                (
                    "activated_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.school"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuardianFamilyInvitationChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_child",
                        to="parents.guardianactivation",
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="parents.guardianfamilyinvitation",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.school"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="students.student"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="guardianfamilyinvitation",
            index=models.Index(
                fields=["school", "mobile_hash", "-created_at"], name="family_invitation_queue_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="guardianfamilyinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("consumed_at__isnull", True), ("revoked_at__isnull", True)),
                fields=("school", "mobile_hash"),
                name="uniq_open_family_invitation",
            ),
        ),
        migrations.AddConstraint(
            model_name="guardianfamilyinvitation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("delivery_status__in", ["PENDING", "SENDING", "SENT", "FAILED", "UNKNOWN"])
                ),
                name="family_invitation_delivery_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="guardianfamilyinvitationchild",
            constraint=models.UniqueConstraint(
                fields=("invitation", "student"), name="uniq_family_invitation_child"
            ),
        ),
        migrations.RunPython(forward, backward),
    ]
