# Generated by Django 5.2.17 on 2026-08-19 23:18

import documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('WARNING_LEVEL_1', 'الإنذار الأول'), ('WARNING_LEVEL_2', 'الإنذار الثاني'), ('WARNING_LEVEL_3', 'الإنذار الثالث'), ('ATTENDANCE_COMMITMENT', 'تعهد الالتزام بالحضور'), ('ABSENCE_DETAIL_REPORT', 'كشف تفصيلي للغياب'), ('MORNING_LATE_DETAIL_REPORT', 'كشف تفصيلي للتأخر الصباحي'), ('PERIOD_LATE_DETAIL_REPORT', 'كشف تفصيلي لتأخر الحصص'), ('STUDENT_ATTENDANCE_REPORT', 'تقرير مواظبة الطالب')], max_length=32)),
                ('template_key', models.CharField(max_length=64)),
                ('template_version', models.CharField(max_length=10)),
                ('snapshot_schema_version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'قيد الإنشاء'), ('READY', 'جاهز'), ('FAILED', 'فشل الإنشاء'), ('VOIDED', 'ملغى')], default='PENDING', max_length=10)),
                ('snapshot_data', models.JSONField(default=dict)),
                ('file', models.FileField(blank=True, null=True, storage=documents.storage.PrivateDocumentStorage, upload_to=documents.storage.generated_document_path)),
                ('mime_type', models.CharField(blank=True, default='', max_length=50)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('revision', models.PositiveSmallIntegerField(default=1)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'verbose_name': 'مستند مولد',
                'verbose_name_plural': 'المستندات المولدة',
            },
        ),
    ]
