# Generated by Django 5.2.17 on 2026-08-19 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('memberships', '0002_alter_schoolmembership_status'),
        ('schools', '0003_schoolsettings_morning_late_grace_minutes_and_more'),
        ('student_actions', '0001_initial'),
        ('student_warnings', '0001_initial'),
        ('students', '0003_section_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='student_actions.studentaction'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='generated_by_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='memberships.schoolmembership'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='schools.school'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='students.student'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='voided_by_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='memberships.schoolmembership'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='warning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='student_warnings.studentwarning'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['school', 'student', '-generated_at'], name='doc_school_student_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['school', 'document_type'], name='doc_school_type_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['warning'], name='doc_warning_idx'),
        ),
        migrations.AddConstraint(
            model_name='generateddocument',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'READY'])), fields=('warning', 'document_type', 'revision'), name='uniq_live_warning_document'),
        ),
        migrations.AddConstraint(
            model_name='generateddocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'READY'), _negated=True), models.Q(('file__isnull', False), models.Q(('file', ''), _negated=True)), _connector='OR'), name='document_ready_requires_file'),
        ),
    ]
