# Generated by Django 5.2.17 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("documents", "0002_initial")]

    operations = [
        migrations.AlterField(
            model_name="generateddocument",
            name="snapshot_schema_version",
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
