# Generated by Django 5.2.17 on 2026-08-18 17:46

import django.db.models.deletion
import staff.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("memberships", "0002_alter_schoolmembership_status"),
        ("schools", "0002_schoolsettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=staff.models.staff_import_file_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "مرفوع"),
                            ("PROCESSING", "قيد المعالجة"),
                            ("READY_FOR_REVIEW", "جاهز للمراجعة"),
                            ("IMPORTING", "جارٍ الاستيراد"),
                            ("COMPLETED", "مكتمل"),
                            ("FAILED", "فشل"),
                            ("CANCELLED", "ملغى"),
                        ],
                        default="UPLOADED",
                        max_length=20,
                    ),
                ),
                ("column_mapping", models.JSONField(blank=True, default=dict)),
                ("headers", models.JSONField(blank=True, default=list)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("valid_rows", models.PositiveIntegerField(default=0)),
                ("invalid_rows", models.PositiveIntegerField(default=0)),
                ("duplicate_rows", models.PositiveIntegerField(default=0)),
                ("new_user_rows", models.PositiveIntegerField(default=0)),
                ("existing_user_rows", models.PositiveIntegerField(default=0)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, default="", max_length=50)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_import_jobs",
                        to="schools.school",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "مهمة استيراد موظفين",
                "verbose_name_plural": "مهام استيراد الموظفين",
            },
        ),
        migrations.CreateModel(
            name="StaffImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("mobile", models.CharField(blank=True, default="", max_length=16)),
                ("data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "معلم جديد"),
                            ("EXISTING_USER_INVITE", "حساب موجود — دعوة"),
                            ("ADD_TEACHER_ROLE", "إضافة دور معلم"),
                            ("PROFILE_UPDATE", "تحديث بيانات"),
                            ("EXISTING_UNCHANGED", "بلا تغيير"),
                            ("INVITATION_PENDING", "دعوة قائمة"),
                            ("NEEDS_MANUAL_ACTION", "يتطلب إجراء يدويًا"),
                            ("ERROR", "خطأ"),
                            ("DUPLICATE_IN_FILE", "مكرر في الملف"),
                        ],
                        max_length=30,
                    ),
                ),
                ("error_codes", models.JSONField(blank=True, default=list)),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="staff.staffimportjob",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number"],
            },
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "display_name",
                    models.CharField(max_length=200, verbose_name="اسم العرض"),
                ),
                (
                    "employee_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("job_title", models.CharField(blank=True, default="", max_length=100)),
                (
                    "source",
                    models.CharField(
                        choices=[("IMPORT", "استيراد"), ("MANUAL", "يدوي")],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "membership",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to="memberships.schoolmembership",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profiles",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف موظف",
                "verbose_name_plural": "ملفات الموظفين",
            },
        ),
        migrations.AddIndex(
            model_name="staffimportjob",
            index=models.Index(
                fields=["school", "status"], name="staff_import_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="staffimportjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PROCESSING", "IMPORTING"])),
                fields=("school",),
                name="uniq_running_staff_import_per_school",
            ),
        ),
        migrations.AddIndex(
            model_name="staffimportrow",
            index=models.Index(
                fields=["job", "status"], name="staff_row_job_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffprofile",
            index=models.Index(
                fields=["school", "display_name"], name="staff_school_name_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="staffprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("employee_number__isnull", False)),
                fields=("school", "employee_number"),
                name="uniq_employee_number_per_school",
            ),
        ),
    ]
