# Generated by Django 5.2.17 on 2026-08-19 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0002_alter_schoolmembership_status'),
        ('schools', '0003_schoolsettings_morning_late_grace_minutes_and_more'),
        ('student_warnings', '0001_initial'),
        ('students', '0003_section_qr_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('PARENT_CONTACT', 'التواصل مع ولي الأمر'), ('STUDENT_MEETING', 'مقابلة الطالب'), ('PARENT_MEETING', 'مقابلة ولي الأمر'), ('COMMITMENT_TAKEN', 'أخذ تعهد'), ('WARNING_DELIVERED', 'تسليم إنذار'), ('ADMINISTRATIVE_NOTE', 'ملاحظة إدارية'), ('OTHER', 'إجراء آخر')], max_length=24)),
                ('status', models.CharField(choices=[('COMPLETED', 'منفذ'), ('CANCELLED', 'ملغى')], default='COMPLETED', max_length=12)),
                ('performed_at', models.DateTimeField()),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=300)),
                ('cancelled_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='memberships.schoolmembership')),
                ('performed_by_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='memberships.schoolmembership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_actions', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='students.student')),
                ('warning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='student_warnings.studentwarning')),
            ],
            options={
                'verbose_name': 'إجراء طلابي',
                'verbose_name_plural': 'الإجراءات الطلابية',
                'indexes': [models.Index(fields=['school', 'student', '-performed_at'], name='action_school_student_idx'), models.Index(fields=['school', 'action_type'], name='action_school_type_idx'), models.Index(fields=['warning'], name='action_warning_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', True), ('status', 'COMPLETED')), models.Q(('cancelled_at__isnull', False), ('status', 'CANCELLED')), _connector='OR'), name='action_cancelled_requires_timestamp')],
            },
        ),
    ]
