# Generated by Django 5.2.17 on 2026-08-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaction',
            name='action_type',
            field=models.CharField(choices=[('PARENT_CONTACT', 'التواصل مع ولي الأمر'), ('STUDENT_MEETING', 'مقابلة الطالب'), ('PARENT_MEETING', 'مقابلة ولي الأمر'), ('COMMITMENT_TAKEN', 'أخذ تعهد'), ('WARNING_DELIVERED', 'تسليم إنذار'), ('REFERRED_TO_COUNSELOR', 'إحالة إلى المرشد الطلابي'), ('ADMINISTRATIVE_NOTE', 'ملاحظة إدارية'), ('OTHER', 'إجراء آخر')], max_length=24),
        ),
    ]
